package com.mbeddr.ext.components.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.baseLanguage.closures.runtime.Wrappers;
import de.itemis.mps.editor.diagram.runtime.model.EditorCell_DiagramElement;
import de.itemis.mps.editor.diagram.runtime.ContextVariables;
import java.util.List;
import de.itemis.mps.editor.diagram.runtime.model.Port;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import com.mbeddr.ext.components.behavior.AbstractInstance__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import com.mbeddr.ext.components.behavior.AbstractInstanceConfiguration__BehaviorDescriptor;
import com.mbeddr.ext.components.behavior.AssemblyConnector__BehaviorDescriptor;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import de.itemis.mps.editor.diagram.runtime.jgraph.MyGraph;
import de.itemis.mps.editor.diagram.runtime.jgraph.DiagramCreationContext;
import de.itemis.mps.editor.diagram.runtime.jgraph.ElkLayouter;
import de.itemis.mps.editor.diagram.runtime.shape.IShape;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import de.itemis.mps.editor.diagram.runtime.model.SNodeBoxAccessor;
import de.itemis.mps.editor.diagram.runtime.model.IDiagramElementAccessor;
import de.itemis.mps.editor.diagram.runtime.model.IAccessorFactory;
import java.util.Collections;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Vertical;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.editor.runtime.style.CellAlign;
import com.mbeddr.ext.components.behavior.Component__BehaviorDescriptor;
import jetbrains.mps.nodeEditor.EditorSettings;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Horizontal;
import jetbrains.mps.nodeEditor.AbstractCellProvider;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import com.mbeddr.core.base.editor.VerticalWhitespaceCell;
import jetbrains.mps.nodeEditor.cells.EditorCell_Indent;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.openapi.editor.menus.transformation.SPropertyInfo;
import jetbrains.mps.nodeEditor.cells.EditorCell_Property;
import jetbrains.mps.nodeEditor.cells.SPropertyAccessor;
import com.mbeddr.ext.components.editor.ComponentStyles_StyleSheet.ComponentStyleClass;
import jetbrains.mps.nodeEditor.cellMenu.SPropertySubstituteInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;
import java.util.Objects;
import jetbrains.mps.lang.core.behavior.PropertyAttribute__BehaviorDescriptor;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.openapi.editor.update.AttributeKind;
import java.awt.Color;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.lang.editor.cellProviders.SReferenceCellProvider;
import jetbrains.mps.editor.runtime.impl.CellUtil;
import jetbrains.mps.nodeEditor.cellMenu.SReferenceSubstituteInfo;
import jetbrains.mps.lang.core.behavior.LinkAttribute__BehaviorDescriptor;
import de.itemis.mps.editor.diagram.runtime.CompartmentCell;
import de.itemis.mps.editor.diagram.styles.editor.LineStyle;
import jetbrains.mps.nodeEditor.cellProviders.AbstractCellListHandler;
import jetbrains.mps.lang.editor.cellProviders.RefNodeListHandler;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.openapi.editor.menus.transformation.SNodeLocation;
import jetbrains.mps.openapi.editor.cells.DefaultSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SEmptyContainmentSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SChildSubstituteInfo;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.nodeEditor.cellActions.CellAction_DeleteNode;
import com.mbeddr.mpsutil.editor.querylist.runtime.QueryListHandler;
import com.mbeddr.mpsutil.editor.querylist.runtime.EditorCell_QueryList;
import org.jetbrains.mps.openapi.language.SConceptFeature;
import jetbrains.mps.openapi.editor.cells.SubstituteInfo;
import com.mbeddr.mpsutil.editor.querylist.runtime.SubstituteInfoFactory;
import de.slisson.mps.hacks.editor.DummyReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

/*package*/ class ComponentInstance_graphicalWiring_EditorBuilder_a extends AbstractEditorBuilder {
  @NotNull
  private SNode myNode;

  public ComponentInstance_graphicalWiring_EditorBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createDiagramNode_1();
  }

  private EditorCell createDiagramNode_0(final EditorContext editorContext, final SNode node) {

    final Wrappers._T<EditorCell_DiagramElement> editorCell = new Wrappers._T<EditorCell_DiagramElement>(null);

    ContextVariables.withValue("thisNode", node, () -> {
      final ContextVariables _variablesContext = ContextVariables.getCurrent();
      final List<Port> ports = new ArrayList<Port>();
      for (final SNode portObject : Sequence.fromIterable(SNodeOperations.ofConcept(AbstractInstance__BehaviorDescriptor.getInputPorts_id7nJums3A_gz.invoke(((SNode) _variablesContext.getValue("thisNode"))), CONCEPTS.Port$R5))) {
        ContextVariables.withParentAndValue(_variablesContext, "portObject", portObject, new Runnable() {
          public void run() {
            final ContextVariables _variablesContext = ContextVariables.getCurrent();
            {
              Port port = new Port(SPropertyOperations.getString(((SNode) _variablesContext.getValue("portObject")), PROPS.name$MnvL));
              port.setShape(new PortShape(Sequence.fromIterable(AbstractInstanceConfiguration__BehaviorDescriptor.assemblyConnectors_id6JVEnxIhC2V.invoke(SNodeOperations.getNodeAncestor(((SNode) _variablesContext.getValue("thisNode")), CONCEPTS.AbstractInstanceConfiguration$QD, false, false))).any((it) -> (boolean) AssemblyConnector__BehaviorDescriptor.hasAsTarget_id5meTu9orL8n.invoke(it, ((SNode) _variablesContext.getValue("thisNode")), ((SNode) _variablesContext.getValue("portObject")))), false, false));
              {
                SNode parameterObject = portObject;
                port.setTooltipCell(new Inline_Builder_bg8oxe_a0a0(editorContext, parameterObject).createCell());
              }
              port.setSNodeAndDummyCell(portObject, editorContext);
              Style style = new StyleImpl();
              MyGraph rootGraph = DiagramCreationContext.getRootGraph();
              if (port.getBox() != null && rootGraph != null) {
                ElkLayouter layouter = (ElkLayouter) rootGraph.getRootDiagramModel().getLayouter();
                layouter.addPortsStyle(style, port.getBox().getAccessor().getId());
              }
              ports.add(port);
            }
          }
        });
      }
      for (final SNode portObject : Sequence.fromIterable(SNodeOperations.ofConcept(AbstractInstance__BehaviorDescriptor.getOutputPorts_id7nJums3AVys.invoke(((SNode) _variablesContext.getValue("thisNode"))), CONCEPTS.Port$R5))) {
        ContextVariables.withParentAndValue(_variablesContext, "portObject", portObject, new Runnable() {
          public void run() {
            final ContextVariables _variablesContext = ContextVariables.getCurrent();
            {
              Port port = new Port(SPropertyOperations.getString(((SNode) _variablesContext.getValue("portObject")), PROPS.name$MnvL));
              port.setRelativeX(1.0);
              port.setShape(new PortShape(Sequence.fromIterable(AbstractInstanceConfiguration__BehaviorDescriptor.assemblyConnectors_id6JVEnxIhC2V.invoke(SNodeOperations.getNodeAncestor(((SNode) _variablesContext.getValue("thisNode")), CONCEPTS.AbstractInstanceConfiguration$QD, false, false))).any((it) -> (boolean) AssemblyConnector__BehaviorDescriptor.hasAsSource_id2ZUGF54kZL1.invoke(it, ((SNode) _variablesContext.getValue("thisNode")), ((SNode) _variablesContext.getValue("portObject")))), true, (SNodeOperations.isInstanceOf(((SNode) _variablesContext.getValue("portObject")), CONCEPTS.RequiredPort$Si) ? SPropertyOperations.getBoolean(SNodeOperations.cast(((SNode) _variablesContext.getValue("portObject")), CONCEPTS.RequiredPort$Si), PROPS.optional$mTHR) : false)));
              {
                SNode parameterObject = portObject;
                port.setTooltipCell(new Inline_Builder_bg8oxe_a0b0(editorContext, parameterObject).createCell());
              }
              port.setSNodeAndDummyCell(portObject, editorContext);
              Style style = new StyleImpl();
              MyGraph rootGraph = DiagramCreationContext.getRootGraph();
              if (port.getBox() != null && rootGraph != null) {
                ElkLayouter layouter = (ElkLayouter) rootGraph.getRootDiagramModel().getLayouter();
                layouter.addPortsStyle(style, port.getBox().getAccessor().getId());
              }
              ports.add(port);
            }
          }
        });
      }

      EditorCell contentCell = createCollection_0();
      final List<EditorCell> contentCells = new ArrayList<EditorCell>();
      contentCells.add(contentCell);
      final IShape shape = new ComponentInstanceShape(Sequence.fromIterable(AbstractInstance__BehaviorDescriptor.getInputPorts_id7nJums3A_gz.invoke(((SNode) _variablesContext.getValue("thisNode")))).isEmpty(), Sequence.fromIterable(AbstractInstance__BehaviorDescriptor.getOutputPorts_id7nJums3AVys.invoke(((SNode) _variablesContext.getValue("thisNode")))).isEmpty(), !(SNodeOperations.isInstanceOf(SLinkOperations.getTarget(((SNode) _variablesContext.getValue("thisNode")), LINKS.component$ikVC), CONCEPTS.AtomicComponent$ym)));


      SNodeBoxAccessor accessor = new SNodeBoxAccessor(node) {
        @NotNull
        public List<Port> getPorts() {
          return ports;
        }
        public IShape getShape() {
          return shape;
        }
        @Override
        @NotNull
        public List<EditorCell> getContentCells() {
          if (contentCells.isEmpty()) {
            contentCells.add(getRootEditorCell());
          }
          return contentCells;
        }

        public List<? extends IDiagramElementAccessor> getElements(IAccessorFactory accessorFactory) {
          final List<IDiagramElementAccessor> elements = new ArrayList<IDiagramElementAccessor>();
          return elements;
        }



        @NotNull
        @Override
        public Iterable<SNode> getNavigationTargets() {
          Iterable<SNode> result = Sequence.fromIterable(Collections.<SNode>emptyList());
          result = Sequence.fromIterable(result).concat(Sequence.fromIterable(Sequence.<SNode>singleton(SLinkOperations.getTarget(((SNode) _variablesContext.getValue("thisNode")), LINKS.component$ikVC))));
          return result;
        }
        @Override
        public boolean allowScaling() {
          return false;
        }


      };

      editorCell.value = new EditorCell_DiagramElement(editorContext, node, accessor);
      editorCell.value.setCellId("DiagramNode_bg8oxe_a");
      editorCell.value.setBig(true);
      setCellContext(editorCell.value);

      editorCell.value.addEditorCell(contentCell);
      MyGraph rootGraph = DiagramCreationContext.getRootGraph();
      if (rootGraph != null) {
        ElkLayouter layouter = (ElkLayouter) rootGraph.getRootDiagramModel().getLayouter();
        layouter.addNodesStyle(editorCell.value.getStyle(), accessor.getId());
      }
    });

    return editorCell.value;
  }
  private EditorCell createDiagramNode_1() {
    return createDiagramNode_0(getEditorContext(), myNode);
  }
  private EditorCell createCollection_0() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Vertical());
    editorCell.setCellId("Collection_bg8oxe_a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, true);
    style.set(StyleAttributes.HORIZONTAL_ALIGN, CellAlign.CENTER);
    style.set(StyleAttributes.FONT_SIZE, _StyleParameter_QueryFunction_bg8oxe_a2a0());
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(createCollection_1());
    editorCell.addEditorCell(createCollection_2());
    if (nodeCondition_bg8oxe_a2a0()) {
      editorCell.addEditorCell(createCollection_5());
    }
    editorCell.addEditorCell(createCustom_3());
    return editorCell;
  }
  private boolean nodeCondition_bg8oxe_a2a0() {
    return Sequence.fromIterable(Component__BehaviorDescriptor.allInitFields_id7BIOMJxqwh7.invoke(SLinkOperations.getTarget(myNode, LINKS.component$ikVC))).isNotEmpty();
  }
  private int _StyleParameter_QueryFunction_bg8oxe_a2a0() {
    return ((int) (EditorSettings.getInstance().getFontSize() * 0.9));
  }
  private EditorCell createCollection_1() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Horizontal());
    editorCell.setCellId("Collection_bg8oxe_a0a");
    editorCell.addEditorCell(createCustom_0());
    return editorCell;
  }
  private EditorCell createCustom_0() {
    AbstractCellProvider provider = ((_FunctionTypes._return_P0_E0<VerticalWhitespaceCell>) () -> new VerticalWhitespaceCell(myNode, 0)).invoke();
    EditorCell editorCell = provider.createEditorCell(getEditorContext());
    editorCell.setCellId("Custom_bg8oxe_a0a0");
    return editorCell;
  }
  private EditorCell createCollection_2() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Horizontal());
    editorCell.setCellId("Collection_bg8oxe_b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.HORIZONTAL_ALIGN, CellAlign.CENTER);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(createIndentCell_0());
    editorCell.addEditorCell(createCollection_3());
    editorCell.addEditorCell(createIndentCell_1());
    return editorCell;
  }
  private EditorCell createIndentCell_0() {
    EditorCell_Indent editorCell = new EditorCell_Indent(getEditorContext(), myNode);
    return editorCell;
  }
  private EditorCell createCollection_3() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Vertical());
    editorCell.setCellId("Collection_bg8oxe_b1a0");
    editorCell.addEditorCell(createCollection_4());
    editorCell.addEditorCell(createRefCell_0());
    return editorCell;
  }
  private EditorCell createCollection_4() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Horizontal());
    editorCell.setCellId("Collection_bg8oxe_a1b0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    style.set(StyleAttributes.HORIZONTAL_ALIGN, CellAlign.CENTER);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(createProperty_0());
    return editorCell;
  }
  private EditorCell createProperty_0() {
    getCellFactory().pushCellContext();
    try {
      final SProperty property = PROPS.name$MnvL;
      getCellFactory().setPropertyInfo(new SPropertyInfo(myNode, property));
      EditorCell_Property editorCell = EditorCell_Property.create(getEditorContext(), new SPropertyAccessor(myNode, property, false, false), myNode);
      editorCell.setDefaultText("<no name>");
      editorCell.setCellId("property_name");
      Style style = new StyleImpl();
      new ComponentStyleClass(this).apply(style, editorCell);
      style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(_StyleParameter_QueryFunction_bg8oxe_a0a0b1a0()));
      editorCell.getStyle().putAll(style);
      editorCell.setSubstituteInfo(new SPropertySubstituteInfo(editorCell, property));
      setCellContext(editorCell);
      Iterable<SNode> propertyAttributes = SNodeOperations.ofConcept(new IAttributeDescriptor.AllAttributes().list(myNode), CONCEPTS.PropertyAttribute$Gb);
      Iterable<SNode> currentPropertyAttributes = Sequence.fromIterable(propertyAttributes).where((it) -> Objects.equals(PropertyAttribute__BehaviorDescriptor.getProperty_id1avfQ4BBzOo.invoke(it), property));
      if (Sequence.fromIterable(currentPropertyAttributes).isNotEmpty()) {
        EditorManager manager = EditorManager.getInstanceFromContext(getEditorContext());
        return manager.createNodeRoleAttributeCell(Sequence.fromIterable(currentPropertyAttributes).first(), AttributeKind.PROPERTY, editorCell);
      } else
      return editorCell;
    } finally {
      getCellFactory().popCellContext();
    }
  }
  private Color _StyleParameter_QueryFunction_bg8oxe_a0a0b1a0() {
    return DiagramColors.COMPONENT_TEXT;
  }
  private EditorCell createRefCell_0() {
    final SReferenceLink referenceLink = LINKS.component$ikVC;
    SReferenceCellProvider provider = new SReferenceCellProvider(getNode(), referenceLink, getEditorContext()) {
      protected EditorCell createReferenceCell(final SNode targetNode) {
        EditorCell cell = getUpdateSession().updateReferencedNodeCell(() -> new Inline_Builder0(getEditorContext(), getNode(), targetNode).createCell(), targetNode, LINKS.component$ikVC);
        CellUtil.setupIDeprecatableStyles(targetNode, cell);
        setSemanticNodeToCells(cell, getNode());
        installDeleteActions_notnull(cell);
        return cell;
      }
    };

    provider.setNoTargetText("<no component>");
    EditorCell editorCell = provider.createCell();

    if (editorCell.getSRole() == null) {
      editorCell.setReferenceCell(true);
      editorCell.setSRole(LINKS.component$ikVC);
    }
    editorCell.setSubstituteInfo(new SReferenceSubstituteInfo(editorCell, referenceLink));
    Iterable<SNode> referenceAttributes = SNodeOperations.ofConcept(new IAttributeDescriptor.AllAttributes().list(myNode), CONCEPTS.LinkAttribute$v_);
    Iterable<SNode> currentReferenceAttributes = Sequence.fromIterable(referenceAttributes).where((it) -> Objects.equals(LinkAttribute__BehaviorDescriptor.getLink_id1avfQ4BEFo6.invoke(it), referenceLink));
    if (Sequence.fromIterable(currentReferenceAttributes).isNotEmpty()) {
      EditorManager manager = EditorManager.getInstanceFromContext(getEditorContext());
      return manager.createNodeRoleAttributeCell(Sequence.fromIterable(currentReferenceAttributes).first(), AttributeKind.REFERENCE, editorCell);
    } else
    return editorCell;
  }
  /*package*/ static class Inline_Builder0 extends AbstractEditorBuilder {
    @NotNull
    private SNode myNode;
    private SNode myReferencingNode;

    /*package*/ Inline_Builder0(@NotNull EditorContext context, SNode referencingNode, @NotNull SNode node) {
      super(context);
      myReferencingNode = referencingNode;
      myNode = node;
    }

    /*package*/ EditorCell createCell() {
      return createProperty_1();
    }

    @NotNull
    @Override
    public SNode getNode() {
      return myNode;
    }

    private EditorCell createProperty_1() {
      getCellFactory().pushCellContext();
      try {
        final SProperty property = PROPS.name$MnvL;
        getCellFactory().setPropertyInfo(new SPropertyInfo(myNode, property));
        EditorCell_Property editorCell = EditorCell_Property.create(getEditorContext(), new SPropertyAccessor(myNode, property, true, false), myNode);
        editorCell.setDefaultText("<no name>");
        editorCell.setCellId("property_name1");
        Style style = new StyleImpl();
        new ComponentStyleClass(this).apply(style, editorCell);
        style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(_StyleParameter_QueryFunction_bg8oxe_a0a0b1b0a()));
        editorCell.getStyle().putAll(style);
        editorCell.setSubstituteInfo(new SPropertySubstituteInfo(editorCell, property));
        setCellContext(editorCell);
        Iterable<SNode> propertyAttributes = SNodeOperations.ofConcept(new IAttributeDescriptor.AllAttributes().list(myNode), CONCEPTS.PropertyAttribute$Gb);
        Iterable<SNode> currentPropertyAttributes = Sequence.fromIterable(propertyAttributes).where((it) -> Objects.equals(PropertyAttribute__BehaviorDescriptor.getProperty_id1avfQ4BBzOo.invoke(it), property));
        if (Sequence.fromIterable(currentPropertyAttributes).isNotEmpty()) {
          EditorManager manager = EditorManager.getInstanceFromContext(getEditorContext());
          return manager.createNodeRoleAttributeCell(Sequence.fromIterable(currentPropertyAttributes).first(), AttributeKind.PROPERTY, editorCell);
        } else
        return editorCell;
      } finally {
        getCellFactory().popCellContext();
      }
    }
    private Color _StyleParameter_QueryFunction_bg8oxe_a0a0b1b0a() {
      return DiagramColors.COMPONENT_TEXT;
    }
  }
  private EditorCell createIndentCell_1() {
    EditorCell_Indent editorCell = new EditorCell_Indent(getEditorContext(), myNode);
    return editorCell;
  }
  private EditorCell createCollection_5() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Vertical());
    editorCell.setCellId("Collection_bg8oxe_c0a");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(createCustom_1());
    editorCell.addEditorCell(createCompartment_1());
    editorCell.addEditorCell(createCustom_2());
    editorCell.addEditorCell(createCollection_6());
    return editorCell;
  }
  private EditorCell createCustom_1() {
    AbstractCellProvider provider = ((_FunctionTypes._return_P0_E0<VerticalWhitespaceCell>) () -> new VerticalWhitespaceCell(myNode, 1)).invoke();
    EditorCell editorCell = provider.createEditorCell(getEditorContext());
    editorCell.setCellId("Custom_bg8oxe_a2a0");
    return editorCell;
  }
  private EditorCell createCompartment_0(EditorContext editorContext, SNode node) {
    CompartmentCell editorCell = new CompartmentCell(editorContext, node);
    editorCell.setCellId("Compartment_bg8oxe_b2a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.getInstance().<Color>getAttribute("de.itemis.mps.editor.diagram.styles", "__line-color"), getStyleRegistry().getSimpleColor(_StyleParameter_QueryFunction_bg8oxe_a0b2a0()));
    style.set(StyleAttributes.getInstance().<Float>getAttribute("de.itemis.mps.editor.diagram.styles", "__line-width"), _StyleParameter_QueryFunction_bg8oxe_a1b2a0());
    style.set(StyleAttributes.getInstance().<LineStyle>getAttribute("de.itemis.mps.editor.diagram.styles", "__line-style"), _StyleParameter_QueryFunction_bg8oxe_a2b2a0());
    editorCell.getStyle().putAll(style);
    return editorCell;
  }
  private EditorCell createCompartment_1() {
    return createCompartment_0(getEditorContext(), myNode);
  }
  private Color _StyleParameter_QueryFunction_bg8oxe_a0b2a0() {
    return DiagramColors.COMPONENT_BORDER;
  }
  private Float _StyleParameter_QueryFunction_bg8oxe_a1b2a0() {
    return 1.0f;
  }
  private LineStyle _StyleParameter_QueryFunction_bg8oxe_a2b2a0() {
    return LineStyle.DASHED;
  }
  private EditorCell createCustom_2() {
    AbstractCellProvider provider = ((_FunctionTypes._return_P0_E0<VerticalWhitespaceCell>) () -> new VerticalWhitespaceCell(myNode, 1)).invoke();
    EditorCell editorCell = provider.createEditorCell(getEditorContext());
    editorCell.setCellId("Custom_bg8oxe_c2a0");
    return editorCell;
  }
  private EditorCell createCollection_6() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Horizontal());
    editorCell.setCellId("Collection_bg8oxe_d2a0");
    editorCell.addEditorCell(createIndentCell_2());
    editorCell.addEditorCell(createRefNodeList_0());
    editorCell.addEditorCell(createIndentCell_3());
    return editorCell;
  }
  private EditorCell createIndentCell_2() {
    EditorCell_Indent editorCell = new EditorCell_Indent(getEditorContext(), myNode);
    return editorCell;
  }
  private EditorCell createRefNodeList_0() {
    AbstractCellListHandler handler = new initializersListHandler_bg8oxe_b3c0a(myNode, getEditorContext());
    EditorCell_Collection editorCell = handler.createCells(new CellLayout_Vertical(), false);
    editorCell.setCellId("refNodeList_initializers");
    Style style = new StyleImpl();
    new ComponentStyleClass(this).apply(style, editorCell);
    style.set(StyleAttributes.FONT_SIZE, _StyleParameter_QueryFunction_bg8oxe_a0b3c0a());
    editorCell.getStyle().putAll(style);
    editorCell.setSRole(handler.getElementSRole());
    return editorCell;
  }
  private static class initializersListHandler_bg8oxe_b3c0a extends RefNodeListHandler {
    @NotNull
    private SNode myNode;

    public initializersListHandler_bg8oxe_b3c0a(SNode ownerNode, EditorContext context) {
      super(context, false);
      myNode = ownerNode;
    }

    @NotNull
    public SNode getNode() {
      return myNode;
    }
    public SContainmentLink getSLink() {
      return LINKS.initializers$gWXm;
    }
    public SAbstractConcept getChildSConcept() {
      return CONCEPTS.AbstractComponentInitializer$_p;
    }

    public EditorCell createNodeCell(SNode elementNode) {
      EditorCell elementCell = getUpdateSession().updateChildNodeCell(elementNode);
      installElementCellActions(elementNode, elementCell, false);
      return elementCell;
    }
    public EditorCell createEmptyCell() {
      getCellFactory().pushCellContext();
      getCellFactory().setNodeLocation(new SNodeLocation.FromParentAndLink(initializersListHandler_bg8oxe_b3c0a.this.getNode(), LINKS.initializers$gWXm));
      try {
        EditorCell emptyCell = null;
        emptyCell = super.createEmptyCell();
        installElementCellActions(null, emptyCell, true);
        setCellContext(emptyCell);
        return emptyCell;
      } finally {
        getCellFactory().popCellContext();
      }
    }

    private static final Object OBJ = new Object();

    public void installElementCellActions(SNode elementNode, EditorCell elementCell, boolean isEmptyCell) {
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_COMPLETE_SET) == null) {
        if (elementCell.getSubstituteInfo() == null || elementCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
          elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_COMPLETE_SET, OBJ);
          elementCell.setSubstituteInfo((isEmptyCell ? new SEmptyContainmentSubstituteInfo(elementCell) : new SChildSubstituteInfo(elementCell)));
        }
      }
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_DELETE_SET) == null) {
        if (elementNode != null) {
          elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_DELETE_SET, OBJ);
          elementCell.setAction(CellActionType.DELETE, new CellAction_DeleteNode(elementNode, CellAction_DeleteNode.DeleteDirection.FORWARD));
        }
      }
      if (elementCell.getUserObject(ELEMENT_CELL_BACKSPACE_SET) == null) {
        if (elementNode != null) {
          elementCell.putUserObject(ELEMENT_CELL_BACKSPACE_SET, OBJ);
          elementCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteNode(elementNode, CellAction_DeleteNode.DeleteDirection.BACKWARD));
        }
      }
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET) == null) {
        if (elementNode != null) {
          elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET, OBJ);
        }
      }
    }
  }
  private int _StyleParameter_QueryFunction_bg8oxe_a0b3c0a() {
    return ((int) (EditorSettings.getInstance().getFontSize() * 0.8));
  }
  private EditorCell createIndentCell_3() {
    EditorCell_Indent editorCell = new EditorCell_Indent(getEditorContext(), myNode);
    return editorCell;
  }
  private EditorCell createCustom_3() {
    AbstractCellProvider provider = ((_FunctionTypes._return_P0_E0<VerticalWhitespaceCell>) () -> new VerticalWhitespaceCell(myNode, 0)).invoke();
    EditorCell editorCell = provider.createEditorCell(getEditorContext());
    editorCell.setCellId("Custom_bg8oxe_d0a");
    return editorCell;
  }
  /*package*/ static class Inline_Builder_bg8oxe_a0a0 extends AbstractEditorBuilder {
    @NotNull
    private SNode myNode;

    /*package*/ Inline_Builder_bg8oxe_a0a0(@NotNull EditorContext context, @NotNull SNode node) {
      super(context);
      myNode = node;
    }

    /*package*/ EditorCell createCell() {
      return createQueryList_1();
    }

    @NotNull
    @Override
    public SNode getNode() {
      return myNode;
    }

    private EditorCell createQueryList_0(final EditorContext editorContext, final SNode node) {

      QueryListHandler handler = new QueryListHandler_bg8oxe_a0a0a(editorContext, node, true);
      EditorCell_QueryList editorCell = handler.createCells(new CellLayout_Horizontal());
      editorCell.setTargeConcept(CONCEPTS.Interface$tq);
      editorCell.setOwner(SNodeOperations.getConcept(node));
      editorCell.setCellId("QueryList_bg8oxe_a0a0a");
      Style style = new StyleImpl();
      style.set(StyleAttributes.READ_ONLY, true);
      editorCell.getStyle().putAll(style);
      return editorCell;

    }
    private EditorCell createQueryList_1() {
      return createQueryList_0(getEditorContext(), myNode);
    }
    private static class QueryListHandler_bg8oxe_a0a0a extends QueryListHandler {
      /**
       * allows node access in the query with ConceptFunctionParameter_node
       */
      private SNode myNode;
      public QueryListHandler_bg8oxe_a0a0a(EditorContext context, SNode ownerNode, boolean readOnly) {
        super(context, ownerNode, readOnly);
        myNode = ownerNode;
      }
      @NotNull
      @Override
      public SNode getNode() {
        return myNode;
      }
      public String getElementRole() {
        return null;
      }
      public SConceptFeature getElementSRole() {
        return null;
      }
      public EditorCell createNodeCell(SNode elementNode) {
        EditorCell elementCell = super.createNodeCell(elementNode);
        this.installElementCellActions(getNode(), elementNode, elementCell, getEditorContext());
        return elementCell;
      }
      @Override
      public EditorCell createEmptyCell() {
        EditorCell emptyCell = null;
        emptyCell = super.createEmptyCell();
        this.installElementCellActions(getNode(), null, emptyCell, getEditorContext());
        return postProcessEmptyCell(emptyCell);
      }
      public void installElementCellActions(SNode listOwner, SNode elementNode, EditorCell elementCell, EditorContext editorContext) {
        if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET) == null) {
          elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET, AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET);
          if (elementNode != null) {

            elementCell.setAction(CellActionType.DELETE, new CellAction_DeleteNode(elementNode));
            elementCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteNode(elementNode));


          }
          if (elementCell.getSubstituteInfo() == null) {
            elementCell.setSubstituteInfo(getSubstituteInfo(elementNode));
          }
        }
      }
      private Object executeQuery(final SNode node, final EditorContext editorContext) {
        return SLinkOperations.getTarget(((SNode) ContextVariables.getCurrent().getValue("portObject")), LINKS.intf$QYND);
      }
      @Override
      public Iterable<SNode> getNodesForList(final SNode node) {
        Object queryResult = executeQuery(node, getEditorContext());
        if (queryResult instanceof Iterable) {
          return (Iterable<SNode>) queryResult;
        } else {
          return Sequence.<SNode>singleton((SNode) queryResult);
        }
      }
      @Override
      public SubstituteInfo getSubstituteInfo(final SNode node, final SNode childNode, final SubstituteInfoFactory factory, final EditorContext editorContext) {
        return factory.forChild(childNode);
      }
      @Override
      public void insertNewNode(final SNode node, final SNode anchorNode, final boolean insertBefore, final EditorContext editorContext) {
      }
      @Override
      public void deleteNode(final SNode node, final SNode nodeToDelete, final EditorContext editorContext) {
      }
      @Override
      protected EditorCell createNodeCellNotNull(final EditorContext context, @NotNull final SNode node) {
        EditorCell cell;
        getCellFactory().pushCellContext();
        try {
          getCellFactory().setNodeLocation(new SNodeLocation.FromNode(node));
          cell = createCellDuplicatesSafe(() -> context.getEditorComponent().getUpdater().getCurrentUpdateSession().updateReferencedNodeCell(() -> context.getEditorComponent().getUpdater().getCurrentUpdateSession().updateChildNodeCell(node), node, new DummyReferenceLink("querylist4097820641243830070")));
        } finally {
          getCellFactory().popCellContext();
        }
        return cell;
      }

      private jetbrains.mps.openapi.editor.cells.EditorCell_Collection wrapWithCollection(EditorCell cell) {
        jetbrains.mps.openapi.editor.cells.EditorCell_Collection collection = EditorCell_Collection.createIndent2(getEditorContext(), getNode());
        collection.addEditorCell(cell);
        return collection;
      }

    }
  }
  /*package*/ static class Inline_Builder_bg8oxe_a0b0 extends AbstractEditorBuilder {
    @NotNull
    private SNode myNode;

    /*package*/ Inline_Builder_bg8oxe_a0b0(@NotNull EditorContext context, @NotNull SNode node) {
      super(context);
      myNode = node;
    }

    /*package*/ EditorCell createCell() {
      return createQueryList_3();
    }

    @NotNull
    @Override
    public SNode getNode() {
      return myNode;
    }

    private EditorCell createQueryList_2(final EditorContext editorContext, final SNode node) {

      QueryListHandler handler = new QueryListHandler_bg8oxe_a0a1a(editorContext, node, true);
      EditorCell_QueryList editorCell = handler.createCells(new CellLayout_Horizontal());
      editorCell.setTargeConcept(CONCEPTS.Interface$tq);
      editorCell.setOwner(SNodeOperations.getConcept(node));
      editorCell.setCellId("QueryList_bg8oxe_a0a1a");
      Style style = new StyleImpl();
      style.set(StyleAttributes.READ_ONLY, true);
      editorCell.getStyle().putAll(style);
      return editorCell;

    }
    private EditorCell createQueryList_3() {
      return createQueryList_2(getEditorContext(), myNode);
    }
    private static class QueryListHandler_bg8oxe_a0a1a extends QueryListHandler {
      /**
       * allows node access in the query with ConceptFunctionParameter_node
       */
      private SNode myNode;
      public QueryListHandler_bg8oxe_a0a1a(EditorContext context, SNode ownerNode, boolean readOnly) {
        super(context, ownerNode, readOnly);
        myNode = ownerNode;
      }
      @NotNull
      @Override
      public SNode getNode() {
        return myNode;
      }
      public String getElementRole() {
        return null;
      }
      public SConceptFeature getElementSRole() {
        return null;
      }
      public EditorCell createNodeCell(SNode elementNode) {
        EditorCell elementCell = super.createNodeCell(elementNode);
        this.installElementCellActions(getNode(), elementNode, elementCell, getEditorContext());
        return elementCell;
      }
      @Override
      public EditorCell createEmptyCell() {
        EditorCell emptyCell = null;
        emptyCell = super.createEmptyCell();
        this.installElementCellActions(getNode(), null, emptyCell, getEditorContext());
        return postProcessEmptyCell(emptyCell);
      }
      public void installElementCellActions(SNode listOwner, SNode elementNode, EditorCell elementCell, EditorContext editorContext) {
        if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET) == null) {
          elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET, AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET);
          if (elementNode != null) {

            elementCell.setAction(CellActionType.DELETE, new CellAction_DeleteNode(elementNode));
            elementCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteNode(elementNode));


          }
          if (elementCell.getSubstituteInfo() == null) {
            elementCell.setSubstituteInfo(getSubstituteInfo(elementNode));
          }
        }
      }
      private Object executeQuery(final SNode node, final EditorContext editorContext) {
        return SLinkOperations.getTarget(((SNode) ContextVariables.getCurrent().getValue("portObject")), LINKS.intf$QYND);
      }
      @Override
      public Iterable<SNode> getNodesForList(final SNode node) {
        Object queryResult = executeQuery(node, getEditorContext());
        if (queryResult instanceof Iterable) {
          return (Iterable<SNode>) queryResult;
        } else {
          return Sequence.<SNode>singleton((SNode) queryResult);
        }
      }
      @Override
      public SubstituteInfo getSubstituteInfo(final SNode node, final SNode childNode, final SubstituteInfoFactory factory, final EditorContext editorContext) {
        return factory.forChild(childNode);
      }
      @Override
      public void insertNewNode(final SNode node, final SNode anchorNode, final boolean insertBefore, final EditorContext editorContext) {
      }
      @Override
      public void deleteNode(final SNode node, final SNode nodeToDelete, final EditorContext editorContext) {
      }
      @Override
      protected EditorCell createNodeCellNotNull(final EditorContext context, @NotNull final SNode node) {
        EditorCell cell;
        getCellFactory().pushCellContext();
        try {
          getCellFactory().setNodeLocation(new SNodeLocation.FromNode(node));
          cell = createCellDuplicatesSafe(() -> context.getEditorComponent().getUpdater().getCurrentUpdateSession().updateReferencedNodeCell(() -> context.getEditorComponent().getUpdater().getCurrentUpdateSession().updateChildNodeCell(node), node, new DummyReferenceLink("querylist4097820641243848154")));
        } finally {
          getCellFactory().popCellContext();
        }
        return cell;
      }

      private jetbrains.mps.openapi.editor.cells.EditorCell_Collection wrapWithCollection(EditorCell cell) {
        jetbrains.mps.openapi.editor.cells.EditorCell_Collection collection = EditorCell_Collection.createIndent2(getEditorContext(), getNode());
        collection.addEditorCell(cell);
        return collection;
      }

    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty optional$mTHR = MetaAdapterFactory.getProperty(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x3e5659cd94a48fa9L, 0x4db287ad754ffcdL, "optional");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AbstractInstanceConfiguration$QD = MetaAdapterFactory.getConcept(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x6bfba9786e466b00L, "com.mbeddr.ext.components.structure.AbstractInstanceConfiguration");
    /*package*/ static final SConcept Port$R5 = MetaAdapterFactory.getConcept(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x3e5659cd94a25d82L, "com.mbeddr.ext.components.structure.Port");
    /*package*/ static final SConcept RequiredPort$Si = MetaAdapterFactory.getConcept(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x3e5659cd94a48fa9L, "com.mbeddr.ext.components.structure.RequiredPort");
    /*package*/ static final SConcept AtomicComponent$ym = MetaAdapterFactory.getConcept(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x3e5659cd94a4de73L, "com.mbeddr.ext.components.structure.AtomicComponent");
    /*package*/ static final SConcept PropertyAttribute$Gb = MetaAdapterFactory.getConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da56L, "jetbrains.mps.lang.core.structure.PropertyAttribute");
    /*package*/ static final SConcept LinkAttribute$v_ = MetaAdapterFactory.getConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da51L, "jetbrains.mps.lang.core.structure.LinkAttribute");
    /*package*/ static final SConcept AbstractComponentInitializer$_p = MetaAdapterFactory.getConcept(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x226fa886b3755e91L, "com.mbeddr.ext.components.structure.AbstractComponentInitializer");
    /*package*/ static final SConcept Interface$tq = MetaAdapterFactory.getConcept(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x3e5659cd94a25d77L, "com.mbeddr.ext.components.structure.Interface");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink component$ikVC = MetaAdapterFactory.getReferenceLink(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x3e5659cd94a4de76L, 0x3e5659cd94a4de77L, "component");
    /*package*/ static final SContainmentLink initializers$gWXm = MetaAdapterFactory.getContainmentLink(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x3e5659cd94a4de76L, 0xae5db91fd71e9ffL, "initializers");
    /*package*/ static final SReferenceLink intf$QYND = MetaAdapterFactory.getReferenceLink(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x3e5659cd94a25d82L, 0x3e5659cd94a25d84L, "intf");
  }
}
