package com.mbeddr.ext.components.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.IncludeSubstituteMenuSubstituteMenuPart;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuLookup;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.NamedSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class PortContentRef_SubstituteMenu extends SubstituteMenuBase {
  public PortContentRef_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for " + "PortContentRef", new SNodePointer("r:a77b09d3-76cb-4b3b-9620-10102158ec08(com.mbeddr.ext.components.editor)", "2751388224255786098")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new SMP_Include_p1s80e_a());
    result.add(new SMP_Subconcepts_p1s80e_b());
    return result;
  }

  public class SMP_Include_p1s80e_a extends IncludeSubstituteMenuSubstituteMenuPart {

    public SMP_Include_p1s80e_a() {
      super(new EditorMenuDescriptorBase("include " + "named substitute menu " + "PortContentRef_SmartReference", new SNodePointer("r:a77b09d3-76cb-4b3b-9620-10102158ec08(com.mbeddr.ext.components.editor)", "2751388224255786099")));
    }

    @Nullable
    @Override
    protected SubstituteMenuLookup getMenuLookup(SubstituteMenuContext _context) {
      final EditorContext editorContext = _context.getEditorContext();
      SAbstractConcept conceptToFindMenuFor = getConceptToFindMenuFor(_context);
      return new NamedSubstituteMenuLookup(LanguageRegistry.getInstance(editorContext.getRepository()), conceptToFindMenuFor, "com.mbeddr.ext.components.editor.PortContentRef_SmartReference");
    }
    private SAbstractConcept getConceptToFindMenuFor(SubstituteMenuContext _context) {
      return CONCEPTS.PortContentRef$1L;
    }
  }
  public class SMP_Subconcepts_p1s80e_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_p1s80e_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "PortContentRef", new SNodePointer("r:a77b09d3-76cb-4b3b-9620-10102158ec08(com.mbeddr.ext.components.editor)", "2751388224255786101")));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.PortContentRef$1L);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept PortContentRef$1L = MetaAdapterFactory.getConcept(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x12151330b6843704L, "com.mbeddr.ext.components.structure.PortContentRef");
  }
}
