package com.mbeddr.ext.components.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class PortVarOpCallExpr_SubstituteMenu extends SubstituteMenuBase {
  public PortVarOpCallExpr_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for PortVarOpCallExpr. Generated from implicit smart reference attribute.", new SNodePointer("r:9596407c-f27a-49d3-abde-3a66293c5b61(com.mbeddr.ext.components.structure)", "1685005713378319841")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_ti17a7_a(), CONCEPTS.PortVarOpCallExpr$ux));
    result.add(new SMP_Subconcepts_ti17a7_b());
    return result;
  }

  public class SMP_ReferenceScope_ti17a7_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_ti17a7_a() {
      super(CONCEPTS.PortVarOpCallExpr$ux, LINKS.operation$jSaZ, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_ti17a7_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_ti17a7_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "PortVarOpCallExpr", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.PortVarOpCallExpr$ux);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept PortVarOpCallExpr$ux = MetaAdapterFactory.getConcept(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x176257c4ce6b1de1L, "com.mbeddr.ext.components.structure.PortVarOpCallExpr");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink operation$jSaZ = MetaAdapterFactory.getReferenceLink(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x707ac195dd618205L, 0x707ac195dd618208L, "operation");
  }
}
