package com.mbeddr.mpsutil.ccmenu.reftarget.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ChangeDescriptionModification = 0;
  public static final int ConditionSelector = 1;
  public static final int IModification = 2;
  public static final int ISelector = 3;
  public static final int ITargetCreationExtension = 4;
  public static final int LinkSelector = 5;
  public static final int ModifierExtension = 6;
  public static final int Parameter_TargetLink = 7;
  public static final int Parameter_conceptToCreate = 8;
  public static final int Parameter_referenceParent = 9;
  public static final int RemoveModification = 10;
  public static final int TargetCreationExtensions = 11;
  public static final int TargetSetupExtension = 12;
  public static final int TargetSetupExtension_CreatedNode = 13;
  public static final int TargetSetupExtension_Function = 14;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xf92af8d71fae4067L, 0x810917acf80f8e58L);
    builder.put(0x2d6d1f84511f8133L, ChangeDescriptionModification);
    builder.put(0x2d6d1f84511f5e06L, ConditionSelector);
    builder.put(0x2d6d1f84511f421dL, IModification);
    builder.put(0x2d6d1f84511f2397L, ISelector);
    builder.put(0x338fb5e34908cce4L, ITargetCreationExtension);
    builder.put(0x2d6d1f84511f30ffL, LinkSelector);
    builder.put(0x2d6d1f84511f2394L, ModifierExtension);
    builder.put(0x2d6d1f84511d59bfL, Parameter_TargetLink);
    builder.put(0x2d6d1f84511d8e9dL, Parameter_conceptToCreate);
    builder.put(0x1f136e7733b0385cL, Parameter_referenceParent);
    builder.put(0x2d6d1f84511f421eL, RemoveModification);
    builder.put(0x338fb5e34908cc98L, TargetCreationExtensions);
    builder.put(0x35c7ad8391717f41L, TargetSetupExtension);
    builder.put(0x35c7ad8391719908L, TargetSetupExtension_CreatedNode);
    builder.put(0x35c7ad8391719907L, TargetSetupExtension_Function);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
