package com.mbeddr.ext.components.mock.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SConcept;

public final class StepAssertion__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x44cc979f39168f58L, "com.mbeddr.ext.components.mock.structure.StepAssertion");

  public static final SMethod<Integer> assertionID_id3Krj9ItiXz5 = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("assertionID").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4331139697889499333L).languageId(0xbaacf87e209c9789L, 0x36a565f13fa042d6L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(assertionID_id3Krj9ItiXz5);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static int assertionID_id3Krj9ItiXz5(@NotNull SNode __thisNode__) {
    return ListSequence.fromList(SNodeOperations.getNodeDescendants(SNodeOperations.getNodeAncestor(__thisNode__, CONCEPTS.SequenceExpectation$V_, false, false), CONCEPTS.StepAssertion$qD, false, new SAbstractConcept[]{})).indexOf(__thisNode__);
  }

  /*package*/ StepAssertion__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((Integer) assertionID_id3Krj9ItiXz5(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept SequenceExpectation$V_ = MetaAdapterFactory.getConcept(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x44cc979f390c71c3L, "com.mbeddr.ext.components.mock.structure.SequenceExpectation");
    /*package*/ static final SConcept StepAssertion$qD = MetaAdapterFactory.getConcept(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x44cc979f39168f58L, "com.mbeddr.ext.components.mock.structure.StepAssertion");
  }
}
