package com.mbeddr.mpsutil.review.annotation.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.ConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.annotations.Nullable;

public final class LanguageConceptSwitch implements ConceptIndex {
  private final LanguageConceptIndex myIndex;
  public static final int CommentAnnotationContainer = 0;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x7a060fae09e04372L, 0xbe366696d6554c0eL);
    builder.put(0x7556ef16fac6bfb4L, CommentAnnotationContainer);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  @Override
  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }

  @Override
  public int index(@Nullable SAbstractConcept c, int missingValue) {
    return myIndex.index(c, missingValue);
  }
}
