package com.mbeddr.ext.components.mock.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new ExpectNoCall_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new ExpectTotalNoOfCalls_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new MockComponent_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new ParamRefExpression_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new ParamterAssertion_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new PhaseChangeStatement_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new PhaseChangeTrigger_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new PhaseExpression_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new PhaseRefExpression_Editor());
      case 9:
        return Collections.<ConceptEditor>singletonList(new SequenceExpectation_Editor());
      case 10:
        return Collections.<ConceptEditor>singletonList(new Step_Editor());
      case 11:
        return Collections.<ConceptEditor>singletonList(new StubComponent_Editor());
      case 12:
        return Collections.<ConceptEditor>singletonList(new StubCounterExpr_Editor());
      case 13:
        return Collections.<ConceptEditor>singletonList(new StubPhase_Editor());
      case 14:
        return Collections.<ConceptEditor>singletonList(new ValidateMock_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new ParamRefExpression_SubstituteMenu());
      case 1:
        return Collections.<SubstituteMenu>singletonList(new PhaseRefExpression_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x1ddb142e3d8df584L), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x44cc979f390c0c2bL), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x1ddb142e3d8c8d61L), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x3c1b4c9b9d48aa2cL), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x44cc979f39168f44L), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x2032313b050b4f0dL), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x57d5544ecd7f4b04L), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x2032313b050a790cL), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x57d5544ecd8033c3L), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x44cc979f390c71c3L), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x44cc979f390c71c5L), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x578779f408669663L), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x578779f40867fe9aL), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x2032313b050a78e4L), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x1ddb142e3d9051dcL)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x3c1b4c9b9d48aa2cL), MetaIdFactory.conceptId(0x36a565f13fa042d6L, 0xbaacf87e209c9789L, 0x57d5544ecd8033c3L)).seal();
}
