package com.mbeddr.doc.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.ListScope;
import com.mbeddr.doc.behavior.IFloating__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;

public class ImgRefWord_Constraints extends BaseConstraintsDescriptor {
  public ImgRefWord_Constraints() {
    super(CONCEPTS.ImgRefWord$hh);
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    BaseReferenceConstraintsDescriptor d0 = new BaseReferenceConstraintsDescriptor(LINKS.image$pzia, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:a5b5b4fe-a87a-44d6-a204-cb07050793ac(com.mbeddr.doc.constraints)", "6386504476136420177");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            return ListScope.forResolvableElements(IFloating__BehaviorDescriptor.visibleImagesInDocument_id5yxqZJwzrdj.invoke(SNodeOperations.asSConcept(CONCEPTS.IFloating$ot), SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.IDocumentLike$h$, false, false)));
          }
        };
      }
    };
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(d0.getReference(), d0);
    return references;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ImgRefWord$hh = MetaAdapterFactory.getConcept(0x2374bc907e3741f1L, 0xa9c4c2e35194c36aL, 0x58a16bfbe08db33fL, "com.mbeddr.doc.structure.ImgRefWord");
    /*package*/ static final SInterfaceConcept IFloating$ot = MetaAdapterFactory.getInterfaceConcept(0x2374bc907e3741f1L, 0xa9c4c2e35194c36aL, 0x41ff53f745fa3cc8L, "com.mbeddr.doc.structure.IFloating");
    /*package*/ static final SInterfaceConcept IDocumentLike$h$ = MetaAdapterFactory.getInterfaceConcept(0x2374bc907e3741f1L, 0xa9c4c2e35194c36aL, 0x5c64b4307041a0cfL, "com.mbeddr.doc.structure.IDocumentLike");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink image$pzia = MetaAdapterFactory.getReferenceLink(0x2374bc907e3741f1L, 0xa9c4c2e35194c36aL, 0x58a16bfbe08db33fL, 0x58a16bfbe08db34eL, "image");
  }
}
