package com.mbeddr.doc.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.ListScope;
import com.mbeddr.doc.behavior.DocumentConfig__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class Resource_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Resource_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Resource$4H, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.path$6g6j, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:a5b5b4fe-a87a-44d6-a204-cb07050793ac(com.mbeddr.doc.constraints)", "6386504476136521427");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          return ListScope.forResolvableElements(DocumentConfig__BehaviorDescriptor.allPaths_id5L$H31Kh1a7.invoke(SLinkOperations.getTarget(SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.IDocumentLike$h$, false, false), LINKS.config$bNXi)));
        }
      };
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Resource$4H = MetaAdapterFactory.getConcept(0x2374bc907e3741f1L, 0xa9c4c2e35194c36aL, 0x58a16bfbe08f3ebfL, "com.mbeddr.doc.structure.Resource");
    /*package*/ static final SInterfaceConcept IDocumentLike$h$ = MetaAdapterFactory.getInterfaceConcept(0x2374bc907e3741f1L, 0xa9c4c2e35194c36aL, 0x5c64b4307041a0cfL, "com.mbeddr.doc.structure.IDocumentLike");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink path$6g6j = MetaAdapterFactory.getReferenceLink(0x2374bc907e3741f1L, 0xa9c4c2e35194c36aL, 0x58a16bfbe08f3ebfL, 0x58a16bfbe08f3ec1L, "path");
    /*package*/ static final SReferenceLink config$bNXi = MetaAdapterFactory.getReferenceLink(0x2374bc907e3741f1L, 0xa9c4c2e35194c36aL, 0x5c64b4307041a0cfL, 0x5c64b4307041a0d0L, "config");
  }
}
