package com.mbeddr.mpsutil.ecoreimporter.runtime.importerruntime;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SModel;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.common.util.URI;
import java.util.Objects;
import com.mbeddr.mpsutil.smodule.runtime.lib.ModelHelper;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import org.jetbrains.mps.openapi.language.SLanguage;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.eclipse.emf.ecore.impl.EClassImpl;
import org.eclipse.emf.ecore.impl.EEnumImpl;

public class MetaModelFreshImporter {
  /*package*/ MetaModelImporterCore runner;
  public MetaModelFreshImporter(SModel currentMdl, boolean genEnumInternalVal, String ecoreFileNm) {
    runner = new MetaModelImporterCore(currentMdl, genEnumInternalVal, ecoreFileNm);
  }

  public void importIntoMPS() {
    EPackage ecoreModel = EMFUtils.getEPackage(URI.createFileURI(runner.ecoreFileName()));
    assert !(Objects.equals(ecoreModel, null));
    importIntoMPS(runner.inputModel(), ecoreModel);
  }

  public void importIntoMPS(SModel structureModel, EPackage ecoremetamodel) {
    ModelHelper.addLanguages(structureModel, ListSequence.fromListAndArray(new ArrayList<SLanguage>(), MetaAdapterFactory.getLanguage(0x77948de36ef9452dL, 0xb392d01403e4086fL, "")));
    for (Object content : ecoremetamodel.eContents()) {
      if (content instanceof EClassImpl) {
        runner.addEclass((EClassImpl) content);
      } else if (content instanceof EEnumImpl) {
        runner.addEEnum((EEnumImpl) content);
      }
    }
    runner.resolveLazyObjects();
  }

}
