package com.mbeddr.mpsutil.editingGuide.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import jetbrains.mps.scope.Scope;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.scope.CompositeScope;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;

public final class ProgramFragment__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x67506b1e43ad47feL, 0xa8e6bc7837e9e11fL, 0x364130dd8794d97aL, "com.mbeddr.mpsutil.editingGuide.structure.ProgramFragment");

  public static final SMethod<SNode> getFragmentRoot_id3p1cdQ7_MOb = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("getFragmentRoot").modifiers(12, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3909459679555038475L).languageId(0xa8e6bc7837e9e11fL, 0x67506b1e43ad47feL).build2();
  public static final SMethod<Scope> getImportedNodes_idPYICs0Yrc9 = new SMethodBuilder<Scope>(new SJavaCompoundTypeImpl(Scope.class)).name("getImportedNodes").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(972419658558321417L).languageId(0xa8e6bc7837e9e11fL, 0x67506b1e43ad47feL).build2(SMethodBuilder.createJavaParameter((Class<SAbstractConcept>) ((Class) Object.class), ""));
  public static final SMethod<Scope> getVisibleNodeExporters_id44LrdWQlKmC = new SMethodBuilder<Scope>(new SJavaCompoundTypeImpl(Scope.class)).name("getVisibleNodeExporters").modifiers(1, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4697655592269317544L).languageId(0xa8e6bc7837e9e11fL, 0x67506b1e43ad47feL).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getFragmentRoot_id3p1cdQ7_MOb, getImportedNodes_idPYICs0Yrc9, getVisibleNodeExporters_id44LrdWQlKmC);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static Scope getImportedNodes_idPYICs0Yrc9(@NotNull SNode __thisNode__, final SAbstractConcept targetConcept) {
    Iterable<Scope> scopes = ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.scopeProviders$uJx)).select((it) -> (Scope) ProgramFragment_ScopeProvider__BehaviorDescriptor.getProvidedNodes_id22irgSmHAOg.invoke(it, targetConcept));
    return new CompositeScope(Sequence.fromIterable(scopes).toGenericArray(Scope.class));
  }
  /*package*/ static Scope getVisibleNodeExporters_id44LrdWQlKmC(@NotNull SAbstractConcept __thisConcept__, SNode contextNode) {
    return new ListScope(SModelOperations.nodesIncludingImported(SNodeOperations.getModel(contextNode), CONCEPTS.INodeExporter$W7)) {
      @Override
      public String getName(SNode child) {
        return child.getName();
      }
    };
  }

  /*package*/ ProgramFragment__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 1:
        return (T) ((Scope) getImportedNodes_idPYICs0Yrc9(node, (SAbstractConcept) parameters[0]));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 2:
        return (T) ((Scope) getVisibleNodeExporters_id44LrdWQlKmC(concept, (SNode) parameters[0]));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink scopeProviders$uJx = MetaAdapterFactory.getContainmentLink(0x67506b1e43ad47feL, 0xa8e6bc7837e9e11fL, 0x364130dd8794d97aL, 0xd7eba8700f8f28bL, "scopeProviders");
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept INodeExporter$W7 = MetaAdapterFactory.getInterfaceConcept(0x67506b1e43ad47feL, 0xa8e6bc7837e9e11fL, 0x41316cdf360cea1dL, "com.mbeddr.mpsutil.editingGuide.structure.INodeExporter");
  }
}
