package com.mbeddr.core.base.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class NameSuffix_Constraints extends BaseConstraintsDescriptor {
  /*package*/ NameSuffix_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.NameSuffix$A1, initContext);
    record(new Suffix_PD(this));
  }

  /*package*/ static final class Suffix_PD extends BasePropertyConstraintsDescriptor {
    public Suffix_PD(ConstraintsDescriptor container) {
      super(PROPS.suffix$3D3j, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:7a2f88d6-4108-4d29-b499-cc4de14ea970(com.mbeddr.core.base.constraints)", "2843190776579067676"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      if (propertyValue == null) {
        return true;
      }
      if (propertyValue.matches("[a-zA-Z$[_]][a-zA-Z0-9$[_][-]]*")) {
        return !(CIdentifierHelper.isCKeyword(propertyValue));
      } else {
        return false;
      }
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept NameSuffix$A1 = MetaAdapterFactory.getConcept(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x27750af28aa97cf1L, "com.mbeddr.core.base.structure.NameSuffix");
  }

  private static final class PROPS {
    /*package*/ static final SProperty suffix$3D3j = MetaAdapterFactory.getProperty(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x27750af28aa97cf1L, 0x27750af28aa9801eL, "suffix");
  }
}
