package com.mbeddr.core.pointers.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class VerbatimStringLiteral_Constraints extends BaseConstraintsDescriptor {
  /*package*/ VerbatimStringLiteral_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.VerbatimStringLiteral$$A, initContext);
    record(new Value_PD(this));
  }

  /*package*/ static final class Value_PD extends BasePropertyConstraintsDescriptor {
    public Value_PD(ConstraintsDescriptor container) {
      super(PROPS.value$a7Yf, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:bd926a45-d72f-48d2-9b35-f5586f5ff2bc(com.mbeddr.core.pointers.constraints)", "5355719375892497750"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      return true;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept VerbatimStringLiteral$$A = MetaAdapterFactory.getConcept(0x3bf5377ae9044dedL, 0x97545a516023bfaaL, 0x4a53566584bfc552L, "com.mbeddr.core.pointers.structure.VerbatimStringLiteral");
  }

  private static final class PROPS {
    /*package*/ static final SProperty value$a7Yf = MetaAdapterFactory.getProperty(0x3bf5377ae9044dedL, 0x97545a516023bfaaL, 0x54d65a836190f177L, 0x54d65a836190f17aL, "value");
  }
}
