package com.mbeddr.mpsutil.genreview.highlighting;

/*Generated by MPS */

import java.util.Map;
import jetbrains.mps.baseLanguage.tuples.runtime.Tuples;
import java.awt.Color;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.HashMap;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.baseLanguage.tuples.runtime.MultiTuple;

public class JavaHighlightStrategy extends HighlightingStrategyBase {

  public static void register() {
    HighlightingStrategyManager.registerHighlightingStrategy(".*\\.java", new JavaHighlightStrategy());
  }

  private static Map<Tuples._2<Integer, Color>, List<String>> color2keywords = MapSequence.fromMap(new HashMap<Tuples._2<Integer, Color>, List<String>>());

  static {
    List<String> magentaBoldWords = ListSequence.fromListAndArray(new ArrayList<String>(), "new", "null", "return", "int", "string", "boolean", "double");
    List<String> blueWords = ListSequence.fromListAndArray(new ArrayList<String>(), "import", "package", "void", "public", "private", "protected", "static", "abstract", "for", "if", "else", "class", "final", "switch", "case");
    List<String> orangewords = ListSequence.fromListAndArray(new ArrayList<String>(), "Override");
    MapSequence.fromMap(color2keywords).put(MultiTuple.<Integer,Color>from(BOLD_STYLE, Color.MAGENTA), magentaBoldWords);
    MapSequence.fromMap(color2keywords).put(MultiTuple.<Integer,Color>from(NORMAL_STYLE, Color.BLUE), blueWords);
    MapSequence.fromMap(color2keywords).put(MultiTuple.<Integer,Color>from(NORMAL_STYLE, Color.ORANGE), orangewords);
  }

  @Override
  public Map<Tuples._2<Integer, Color>, List<String>> getAttributes2KeywordsMap() {
    return color2keywords;
  }
}
