package com.mbeddr.cc.requirements.scenarios.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.ReferenceMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import com.mbeddr.cc.requirements.scenarios.behavior.Capability__BehaviorDescriptor;
import jetbrains.mps.errors.BaseQuickFixProvider;
import com.mbeddr.cc.requirements.scenarios.behavior.IDataInstance__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_Call_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_Call_NonTypesystemRule() {
  }
  public void applyRule(final SNode c, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    int expected = ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(c, LINKS.capability$Inkp), LINKS.args$cjlS)).count();
    if (ListSequence.fromList(SLinkOperations.getChildren(c, LINKS.args$QrOQ)).count() != expected) {
      if (SNodeOperations.isInstanceOf(ListSequence.fromList(SLinkOperations.getChildren(c, LINKS.args$QrOQ)).last(), CONCEPTS.IDataInstance$3m)) {
        // this one has an quick fix, the one below does not!
        {
          final MessageTarget errorTarget = new ReferenceMessageTarget(LINKS.capability$Inkp);
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(c, "wrong number of args; expecting " + expected + "   " + Capability__BehaviorDescriptor.signature_id4YQM_89vvUS.invoke(SLinkOperations.getTarget(c, LINKS.capability$Inkp)), "r:d172f314-0f0f-428f-b349-28798381b076(com.mbeddr.cc.requirements.scenarios.typesystem)", "6898387700925512417", null, errorTarget);
          {
            BaseQuickFixProvider intentionProvider = new BaseQuickFixProvider("com.mbeddr.cc.requirements.scenarios.typesystem.addArgument_QuickFix", "6898387700925512431", false);
            intentionProvider.putArgument("cap", SLinkOperations.getTarget(c, LINKS.capability$Inkp));
            intentionProvider.putArgument("dataType", IDataInstance__BehaviorDescriptor.data_id5YVZL2k_jnw.invoke(SNodeOperations.cast(ListSequence.fromList(SLinkOperations.getChildren(c, LINKS.args$QrOQ)).last(), CONCEPTS.IDataInstance$3m)));
            _reporter_2309309498.addIntentionProvider(intentionProvider);
          }
        }
      } else {
        {
          final MessageTarget errorTarget = new ReferenceMessageTarget(LINKS.capability$Inkp);
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(c, "wrong number of args; expecting " + expected + "   " + Capability__BehaviorDescriptor.signature_id4YQM_89vvUS.invoke(SLinkOperations.getTarget(c, LINKS.capability$Inkp)), "r:d172f314-0f0f-428f-b349-28798381b076(com.mbeddr.cc.requirements.scenarios.typesystem)", "5744000828453016336", null, errorTarget);
        }
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.Call$eV;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink capability$Inkp = MetaAdapterFactory.getReferenceLink(0xd6714220402d48cbL, 0xa4a288223c6257f6L, 0x4fb6ca52097b2b30L, 0x4fb6ca52097b5b7fL, "capability");
    /*package*/ static final SContainmentLink args$cjlS = MetaAdapterFactory.getContainmentLink(0xd6714220402d48cbL, 0xa4a288223c6257f6L, 0x4fb6ca52097868a5L, 0x4fb6ca52097868b2L, "args");
    /*package*/ static final SContainmentLink args$QrOQ = MetaAdapterFactory.getContainmentLink(0xd6714220402d48cbL, 0xa4a288223c6257f6L, 0x4fb6ca52097b2b30L, 0x4fb6ca52097d4932L, "args");
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IDataInstance$3m = MetaAdapterFactory.getInterfaceConcept(0xd6714220402d48cbL, 0xa4a288223c6257f6L, 0x5975ee5da3d358a3L, "com.mbeddr.cc.requirements.scenarios.structure.IDataInstance");
    /*package*/ static final SConcept Call$eV = MetaAdapterFactory.getConcept(0xd6714220402d48cbL, 0xa4a288223c6257f6L, 0x4fb6ca52097b2b30L, "com.mbeddr.cc.requirements.scenarios.structure.Call");
  }
}
