package com.mbeddr.core.modules.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.framework.DataFlowAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.lang.dataFlow.framework.DataFlowConstructor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.lang.dataFlow.framework.IDataFlowBuilder;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class DataFlowAspectDescriptorImpl extends DataFlowAspectDescriptorBase {
  @NotNull
  @Override
  public Collection<DataFlowConstructor> getConstructors(String analyzerId) {
    switch (analyzerId) {
      case "com.mbeddr.core.modules.dataFlow.InitializedVariables":
        return Arrays.asList(new DataFlowConstructor[]{new ArgumentRefInitialization(), new ArrayVarRefInitialization(), new DirectAssignmentExpressionInitialization(), new FunctionCallInitialization(), new FunctionRefCallExprInitialization(), new GlobalConstantRefInitialization(), new GlobalVarRefInitialization(), new StatementOutArgumentReadSynthethiser()});
      default:
    }
    return Collections.<DataFlowConstructor>emptyList();
  }

  @NotNull
  @Override
  public Collection<IDataFlowBuilder> getDataFlowBuilders(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<IDataFlowBuilder>singletonList(new AbstractDefineLike_DataFlow());
      case 1:
        return Collections.<IDataFlowBuilder>singletonList(new ArgumentRef_DataFlow());
      case 2:
        return Arrays.asList(new IDataFlowBuilder[]{new Function_DataFlow(), new Function_InterProcedural_BuilderMode_DataFlow()});
      case 3:
        return Arrays.asList(new IDataFlowBuilder[]{new FunctionCall_DataFlow(), new FunctionCall_InterProcedural_BuilderMode_DataFlow()});
      case 4:
        return Collections.<IDataFlowBuilder>singletonList(new FunctionRefCallExpr_DataFlow());
      case 5:
        return Collections.<IDataFlowBuilder>singletonList(new GlobalConstantFunctionRef_DataFlow());
      case 6:
        return Collections.<IDataFlowBuilder>singletonList(new GlobalConstantRef_DataFlow());
      case 7:
        return Collections.<IDataFlowBuilder>singletonList(new GlobalVarRef_DataFlow());
      case 8:
        return Collections.<IDataFlowBuilder>singletonList(new GotoStatement_DataFlow());
      case 9:
        return Collections.<IDataFlowBuilder>singletonList(new ReturnStatement_DataFlow());
      default:
    }
    return Collections.<IDataFlowBuilder>emptyList();
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x2edcb73a870319c4L), MetaIdFactory.conceptId(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x1d0c3765e2e7d0baL), MetaIdFactory.conceptId(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x595522006a5b97e1L), MetaIdFactory.conceptId(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x52941adca601b38cL), MetaIdFactory.conceptId(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x76ad8d576f01e321L), MetaIdFactory.conceptId(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x539093cd747af63aL), MetaIdFactory.conceptId(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x34953142306a769bL), MetaIdFactory.conceptId(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x5bbe8a6d23a20aeaL), MetaIdFactory.conceptId(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x5b797aeeb59e40e0L), MetaIdFactory.conceptId(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x7c747300dbd94ea5L)).seal();
}
