package com.mbeddr.core.modules.dataFlow;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.core.behavior.BaseConcept__BehaviorDescriptor;

public class VariableWrapper {

  public SNode variable;

  /**
   * The value 0 represents the standard type, a value greater than 0 represents the pointer types
   */
  public int indirection;

  public VariableWrapper(SNode variable) {
    this.variable = variable;
    this.indirection = AnalyzerHelper.computeIndirection(variable);
  }

  @Override
  public int hashCode() {
    int hash = 1;
    hash = hash * 17 + ((this.variable == null ? 0 : this.variable.hashCode()));
    hash = hash * 31 + this.indirection;
    return hash;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    } else if (obj == null || obj.getClass() != this.getClass()) {
      return false;
    } else if (this.variable == null) {
      return false;
    } else {
      VariableWrapper that = ((VariableWrapper) obj);
      return this.variable.equals(that.variable) && this.indirection == that.indirection;
    }
  }

  @Override
  public String toString() {
    StringBuffer buffer = new StringBuffer();

    for (int i = 0; i < indirection; i++) {
      buffer.append("*");
    }

    buffer.append(BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(variable));

    return buffer.toString();
  }
}
