package com.mbeddr.mpsutil.editingGuide.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.CompositeScope;
import jetbrains.mps.internal.collections.runtime.Sequence;
import com.mbeddr.mpsutil.editingGuide.behavior.ProgramFragment_ScopeProvider__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import com.mbeddr.mpsutil.editingGuide.behavior.INodeExporter__BehaviorDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;

public class ProgramFragment_ScopeProvider_Element_Constraints extends BaseConstraintsDescriptor {
  public ProgramFragment_ScopeProvider_Element_Constraints() {
    super(CONCEPTS.ProgramFragment_ScopeProvider_Element$fa);
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    BaseReferenceConstraintsDescriptor d0 = new BaseReferenceConstraintsDescriptor(LINKS.target$Ta_o, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:adcd7296-cd7f-4373-b1b1-e2c580647861(com.mbeddr.mpsutil.editingGuide.constraints)", "972419658558302312");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            return new CompositeScope(Sequence.fromIterable(ProgramFragment_ScopeProvider__BehaviorDescriptor.getVisibleDirectNodeExporters_id4fWdCdAZmTB.invoke(SNodeOperations.asSConcept(CONCEPTS.ProgramFragment_ScopeProvider$4y), _context.getContextNode()).getAvailableElements(null)).where((it) -> !(ListSequence.fromList(SNodeOperations.getNodeAncestors(_context.getContextNode(), null, true)).contains(it))).select((it) -> (Scope) INodeExporter__BehaviorDescriptor.getExportedNodes_id79$zShlSHxZ.invoke(SNodeOperations.cast(it, CONCEPTS.INodeExporter$W7), CONCEPTS.BaseConcept$gP)).toGenericArray(Scope.class));
          }
        };
      }
    };
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(d0.getReference(), d0);
    return references;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ProgramFragment_ScopeProvider_Element$fa = MetaAdapterFactory.getConcept(0x67506b1e43ad47feL, 0xa8e6bc7837e9e11fL, 0xd7eba8700f961a9L, "com.mbeddr.mpsutil.editingGuide.structure.ProgramFragment_ScopeProvider_Element");
    /*package*/ static final SConcept ProgramFragment_ScopeProvider$4y = MetaAdapterFactory.getConcept(0x67506b1e43ad47feL, 0xa8e6bc7837e9e11fL, 0xd7eba8700faca3eL, "com.mbeddr.mpsutil.editingGuide.structure.ProgramFragment_ScopeProvider");
    /*package*/ static final SInterfaceConcept INodeExporter$W7 = MetaAdapterFactory.getInterfaceConcept(0x67506b1e43ad47feL, 0xa8e6bc7837e9e11fL, 0x41316cdf360cea1dL, "com.mbeddr.mpsutil.editingGuide.structure.INodeExporter");
    /*package*/ static final SConcept BaseConcept$gP = MetaAdapterFactory.getConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL, "jetbrains.mps.lang.core.structure.BaseConcept");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink target$Ta_o = MetaAdapterFactory.getReferenceLink(0x67506b1e43ad47feL, 0xa8e6bc7837e9e11fL, 0xd7eba8700f961a9L, 0xd7eba8700f961c9L, "target");
  }
}
