package com.mbeddr.ext.components.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SConcept;

public final class RequiredPort__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x3e5659cd94a48fa9L, "com.mbeddr.ext.components.structure.RequiredPort");

  public static final SMethod<String> getPresentation_idhEwIMiw = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("getPresentation").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(1213877396640L).languageId(0x9b92103b95ca8c0cL, 0xceab519525ea4f22L).build2();
  public static final SMethod<String> genStructOpsMemberName_id4WLtQa9fEWO = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("genStructOpsMemberName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5706473467948216116L).languageId(0x97fc7bd73b1f5f40L, 0x97d2424451db4e2eL).build2();
  public static final SMethod<Boolean> isMultiple_id2ZUGF54jY1D = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("isMultiple").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3457272138385317993L).languageId(0x97fc7bd73b1f5f40L, 0x97d2424451db4e2eL).build2();
  public static final SMethod<Boolean> isOptionalOrLowerBoundIsZero_id4qGsbFhUKUr = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("isOptionalOrLowerBoundIsZero").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(5092569226337259163L).languageId(0x97fc7bd73b1f5f40L, 0x97d2424451db4e2eL).build2();
  public static final SMethod<Boolean> isInPort_id2IZ2bWs0yDx = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("isInPort").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3152247881084316257L).languageId(0x97fc7bd73b1f5f40L, 0x97d2424451db4e2eL).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getPresentation_idhEwIMiw, genStructOpsMemberName_id4WLtQa9fEWO, isMultiple_id2ZUGF54jY1D, isOptionalOrLowerBoundIsZero_id4qGsbFhUKUr, isInPort_id2IZ2bWs0yDx);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static String getPresentation_idhEwIMiw(@NotNull SNode __thisNode__) {
    return SPropertyOperations.getString(__thisNode__, PROPS.name$MnvL) + ": " + SPropertyOperations.getString(SLinkOperations.getTarget(__thisNode__, LINKS.intf$QYND), PROPS.name$MnvL);
  }
  /*package*/ static String genStructOpsMemberName_id4WLtQa9fEWO(@NotNull SNode __thisNode__) {
    return SPropertyOperations.getString(__thisNode__, PROPS.name$MnvL) + "__ops";
  }
  /*package*/ static boolean isMultiple_id2ZUGF54jY1D(@NotNull SNode __thisNode__) {
    return SLinkOperations.getTarget(__thisNode__, LINKS.cardinality$DLq9) != null;
  }
  /*package*/ static boolean isOptionalOrLowerBoundIsZero_id4qGsbFhUKUr(@NotNull SNode __thisNode__) {
    if (SPropertyOperations.getBoolean(__thisNode__, PROPS.optional$mTHR)) {
      return true;
    }
    if (((boolean) RequiredPort__BehaviorDescriptor.isMultiple_id2ZUGF54jY1D.invoke(__thisNode__))) {
      return (int) Cardinality__BehaviorDescriptor.lowerBound_id2rnvR93av0K.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.cardinality$DLq9)) == 0;
    }
    return false;
  }
  /*package*/ static boolean isInPort_id2IZ2bWs0yDx(@NotNull SNode __thisNode__) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(__thisNode__, LINKS.intf$QYND), CONCEPTS.SenderReceiverInterface$Vo);
  }

  /*package*/ RequiredPort__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) getPresentation_idhEwIMiw(node));
      case 1:
        return (T) ((String) genStructOpsMemberName_id4WLtQa9fEWO(node));
      case 2:
        return (T) ((Boolean) isMultiple_id2ZUGF54jY1D(node));
      case 3:
        return (T) ((Boolean) isOptionalOrLowerBoundIsZero_id4qGsbFhUKUr(node));
      case 4:
        return (T) ((Boolean) isInPort_id2IZ2bWs0yDx(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink intf$QYND = MetaAdapterFactory.getReferenceLink(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x3e5659cd94a25d82L, 0x3e5659cd94a25d84L, "intf");
    /*package*/ static final SContainmentLink cardinality$DLq9 = MetaAdapterFactory.getContainmentLink(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x3e5659cd94a48fa9L, 0x2ffab2b144517b4dL, "cardinality");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty optional$mTHR = MetaAdapterFactory.getProperty(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x3e5659cd94a48fa9L, 0x4db287ad754ffcdL, "optional");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept SenderReceiverInterface$Vo = MetaAdapterFactory.getConcept(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0xddcc53e97cb37c4L, "com.mbeddr.ext.components.structure.SenderReceiverInterface");
  }
}
