package com.mbeddr.mpsutil.javainterpreter.plugin;

/*Generated by MPS */

import com.mbeddr.mpsutil.interpreter.rt.IEnvironment;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class JavaInterpreterHelper {
  /*package*/ static <T> T storeVariableRef(T value, IEnvironment env, SNode exprNode) {
    if (SNodeOperations.isInstanceOf(exprNode, CONCEPTS.VariableReference$TC)) {
      SNode varRef = SNodeOperations.cast(exprNode, CONCEPTS.VariableReference$TC);
      MapSequence.fromMap(env).put(SLinkOperations.getTarget(varRef, LINKS.variableDeclaration$N1XG), value);
    }
    return value;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept VariableReference$TC = MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink variableDeclaration$N1XG = MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, 0xf8cc6bf960L, "variableDeclaration");
  }
}
