package com.mbeddr.core.util.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_ErrorTypeNotFound_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_ErrorTypeNotFound_NonTypesystemRule() {
  }
  public void applyRule(final SNode etnf, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      final MessageTarget errorTarget = new NodeMessageTarget();
      IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(etnf, "Type not found: " + SPropertyOperations.getString(etnf, PROPS.rawType$Aa2g), "r:167d778b-bddc-4b3f-a776-89718ce72b97(com.mbeddr.core.util.typesystem)", "9107732955310738487", null, errorTarget);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.ErrorTypeNotFound$nc;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class PROPS {
    /*package*/ static final SProperty rawType$Aa2g = MetaAdapterFactory.getProperty(0x2693fc719b0e4b05L, 0xab13f57227d675f2L, 0xac9372e3b5d78f5L, 0xac9372e3b5d8575L, "rawType");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ErrorTypeNotFound$nc = MetaAdapterFactory.getConcept(0x2693fc719b0e4b05L, 0xab13f57227d675f2L, 0xac9372e3b5d78f5L, "com.mbeddr.core.util.structure.ErrorTypeNotFound");
  }
}
