package com.mbeddr.mpsutil.spreferences.runtime;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SModel;
import org.jetbrains.mps.openapi.module.SModuleReference;
import jetbrains.mps.project.Project;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SLanguage;
import jetbrains.mps.smodel.ModelImports;
import jetbrains.mps.smodel.ModuleDependencyVersions;
import jetbrains.mps.smodel.language.LanguageRegistry;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.adapter.MetaAdapterByDeclaration;
import org.jetbrains.mps.openapi.model.SModelReference;
import org.jetbrains.mps.openapi.module.SModule;
import jetbrains.mps.project.AbstractModule;
import org.jetbrains.mps.openapi.model.SNode;

public class SPreferencesUtil {
  /**
   * 
   * @deprecated  use addLanguage(SModelmodelSLanguagelanguage) instead
   */
  @Deprecated
  public static void addLanguage(SModel model, SModuleReference language, Project project) {
    addLanguage(model, MetaAdapterFactory.getLanguage(language), project);
  }
  public static void addLanguage(SModel model, SLanguage language, Project project) {
    ModelImports mi = new ModelImports(model);
    if (mi.getUsedLanguages().contains(language)) {
      return;
    }
    mi.addUsedLanguage(language);

    ModuleDependencyVersions fixer = new ModuleDependencyVersions(project.getComponent(LanguageRegistry.class), project.getRepository());
    fixer.update(model.getModule());

  }
  public static void useLanguage(SModel model, Language language, Project project) {
    addLanguage(model, MetaAdapterByDeclaration.getLanguage(language), project);
  }

  public static void importModel(SModel model, SModelReference modelToImport) {
    new ModelImports(model).addModelImport(modelToImport);
    addDependency(model.getModule(), modelToImport.getModuleReference());
  }
  public static void importModel(SModel model, SModel modelToImport) {
    importModel(model, modelToImport.getReference());
  }

  public static void useDevkit(SModel model, SModuleReference devkit) {
    ModelImports mi = new ModelImports(model);
    if (mi.getUsedDevKits().contains(devkit)) {
      return;
    }
    mi.addUsedDevKit(devkit);
  }
  public static void useDevkit(SModel model, SModule devkit) {
    useDevkit(model, devkit.getModuleReference());
  }


  public static void addLanguage(SModule module, SModuleReference language) {
    // Remove this method: Languages should be imported directly into the model
  }

  public static void addDependency(SModule module, SModuleReference moduleToDependOn) {
    ((AbstractModule) module).addDependency(moduleToDependOn, false);
  }

  public static SNode getFirstRoot(SModel model) {
    for (SNode root : model.getRootNodes()) {
      return root;
    }
    return null;
  }
}
