package com.mbeddr.core.modules.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;

public class FunctionSignature_tooltipHint_njyx9c_b8a0_Editor extends DefaultNodeEditor {
  private Collection<String> myContextHints = Arrays.asList(new String[]{"com.mbeddr.core.modules.editor.GeneratedHints.tooltipHint_njyx9c_b8a0"});
  @Override
  @NotNull
  public Collection<String> getContextHints() {
    return myContextHints;
  }
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return new FunctionSignature_tooltipHint_njyx9c_b8a0_EditorBuilder_a(editorContext, node).createCell();
  }
}
