package com.mbeddr.mpsutil.richstring.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.typesystem.inference.TypeChecker;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import com.mbeddr.mpsutil.richstring.behavior.IInlineFormat__BehaviorDescriptor;
import com.mbeddr.mpsutil.richstring.behavior.IFormatConversionFlag__BehaviorDescriptor;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import com.mbeddr.mpsutil.richstring.behavior.IInlineFormatCategory__BehaviorDescriptor;
import com.mbeddr.mpsutil.richstring.behavior.IFormatConversion__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class check_IFormatConversionFlag_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_IFormatConversionFlag_NonTypesystemRule() {
  }
  public void applyRule(final SNode iFormatConversionFlag, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    SNode inlineFormat = SNodeOperations.getNodeAncestor(iFormatConversionFlag, CONCEPTS.InlineFormat$AE, false, false);
    SNode type = TypeChecker.getInstance().getTypeOf(SLinkOperations.getTarget(inlineFormat, LINKS.expression$i0cs));
    SAbstractConcept category = IInlineFormat__BehaviorDescriptor.calculateCategory2_id38BeNG_3AFp.invoke(inlineFormat);
    SNode conversion = SLinkOperations.getTarget(inlineFormat, LINKS.conversion$hZXr);

    SNode asNode = SNodeOperations.asNode(category);
    // FIXME refactor isApplicable to use concept<> instead of conceptNode<>
    if (!((boolean) IFormatConversionFlag__BehaviorDescriptor.isApplicable_id6Go9U2yx_gX.invoke(iFormatConversionFlag, conversion, (SNode) asNode, type))) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(iFormatConversionFlag, "flag " + IFormatConversionFlag__BehaviorDescriptor.getConversionFlagSymbol_id2UbT3C4ekKT.invoke(iFormatConversionFlag) + " is not applicable for category " + IInlineFormatCategory__BehaviorDescriptor.getExpressionDescription_id6Go9U2yp2P0.invoke(SNodeOperations.asSConcept(category)) + ", conversion " + IFormatConversion__BehaviorDescriptor.getConversionSymbol_id2UbT3C4ekvK.invoke(conversion) + ", argument type " + type, "r:f7af3984-a112-4e63-b8bb-3a0771bf3a31(com.mbeddr.mpsutil.richstring.typesystem)", "7716961532374413220", null, errorTarget);
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.IFormatConversionFlag$53;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept InlineFormat$AE = MetaAdapterFactory.getConcept(0x442d3b7dfe4a4293L, 0xa7c16744d440ecaaL, 0x2e8be43a04395836L, "com.mbeddr.mpsutil.richstring.structure.InlineFormat");
    /*package*/ static final SInterfaceConcept IFormatConversionFlag$53 = MetaAdapterFactory.getInterfaceConcept(0x442d3b7dfe4a4293L, 0xa7c16744d440ecaaL, 0x2e8be43a04393451L, "com.mbeddr.mpsutil.richstring.structure.IFormatConversionFlag");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink expression$i0cs = MetaAdapterFactory.getContainmentLink(0x442d3b7dfe4a4293L, 0xa7c16744d440ecaaL, 0x2e8be43a04395836L, 0x6b1827a0a209a5f8L, "expression");
    /*package*/ static final SContainmentLink conversion$hZXr = MetaAdapterFactory.getContainmentLink(0x442d3b7dfe4a4293L, 0xa7c16744d440ecaaL, 0x2e8be43a04395836L, 0x6b1827a0a209a5f7L, "conversion");
  }
}
