package com.mbeddr.ext.math.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myIRequiresMathConfigItem__BehaviorDescriptor = new IRequiresMathConfigItem__BehaviorDescriptor();
  private final BHDescriptor myLoopVariableReference__BehaviorDescriptor = new LoopVariableReference__BehaviorDescriptor();
  private final BHDescriptor myImplies__BehaviorDescriptor = new Implies__BehaviorDescriptor();
  private final BHDescriptor myMathLoopExpression__BehaviorDescriptor = new MathLoopExpression__BehaviorDescriptor();
  private final BHDescriptor mySqrtExpression__BehaviorDescriptor = new SqrtExpression__BehaviorDescriptor();
  private final BHDescriptor myPowerExpression__BehaviorDescriptor = new PowerExpression__BehaviorDescriptor();
  private final BHDescriptor myLogarithmExpression__BehaviorDescriptor = new LogarithmExpression__BehaviorDescriptor();
  private final BHDescriptor myAbsExpression__BehaviorDescriptor = new AbsExpression__BehaviorDescriptor();
  private final BHDescriptor myFractionExpression__BehaviorDescriptor = new FractionExpression__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myAbsExpression__BehaviorDescriptor;
      case 1:
        return myFractionExpression__BehaviorDescriptor;
      case 2:
        return myIRequiresMathConfigItem__BehaviorDescriptor;
      case 3:
        return myImplies__BehaviorDescriptor;
      case 4:
        return myLogarithmExpression__BehaviorDescriptor;
      case 5:
        return myLoopVariableReference__BehaviorDescriptor;
      case 6:
        return myMathLoopExpression__BehaviorDescriptor;
      case 7:
        return myPowerExpression__BehaviorDescriptor;
      case 8:
        return mySqrtExpression__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xb574d547b77e4fedL, 0x9f60c349c4410765L, 0x46c15b39e5791c4fL), MetaIdFactory.conceptId(0xb574d547b77e4fedL, 0x9f60c349c4410765L, 0x46c15b39e580b7bfL), MetaIdFactory.conceptId(0xb574d547b77e4fedL, 0x9f60c349c4410765L, 0x93f422b8be699eeL), MetaIdFactory.conceptId(0xb574d547b77e4fedL, 0x9f60c349c4410765L, 0x43d39d382969e27aL), MetaIdFactory.conceptId(0xb574d547b77e4fedL, 0x9f60c349c4410765L, 0x46c15b39e5687976L), MetaIdFactory.conceptId(0xb574d547b77e4fedL, 0x9f60c349c4410765L, 0xd7c3339c4eec9a7L), MetaIdFactory.conceptId(0xb574d547b77e4fedL, 0x9f60c349c4410765L, 0x46c15b39e53f4649L), MetaIdFactory.conceptId(0xb574d547b77e4fedL, 0x9f60c349c4410765L, 0x46c15b39e5605eb5L), MetaIdFactory.conceptId(0xb574d547b77e4fedL, 0x9f60c349c4410765L, 0x46c15b39e5567eb9L)).seal();
}
