package com.mbeddr.mpsutil.contextactions.runtime.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.projectplugins.BaseProjectPlugin;
import java.util.List;
import jetbrains.mps.ide.tools.BaseTool;
import com.intellij.openapi.project.Project;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.plugins.part.ProjectPluginPart;

public class Runtime_ProjectPlugin extends BaseProjectPlugin {
  public Runtime_ProjectPlugin() {
  }
  public List<BaseTool> initAllTools1(Project project) {
    List<BaseTool> tools = ListSequence.fromList(new ArrayList<BaseTool>());
    ListSequence.fromList(tools).addElement(new ContextActionsTool_Tool(project));
    return tools;
  }
  public void fillCustomParts(List<ProjectPluginPart> parts) {
    parts.add(new ProjectPlugin_ProjectPluginPart());
  }
}
