package com.mbeddr.cc.var.rt.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_FeatureAttrRefExpr;
  private ConceptPresentation props_FeatureRef;
  private ConceptPresentation props_IConfigModelSelector;
  private ConceptPresentation props_RtFeatureModel;
  private ConceptPresentation props_RtFeatureModelType;
  private ConceptPresentation props_StoreRtConfigStatement;
  private ConceptPresentation props_VarRTConfigItem;
  private ConceptPresentation props_VariantCase;
  private ConceptPresentation props_VariantDefault;
  private ConceptPresentation props_VariantOption;
  private ConceptPresentation props_VariantSwitch;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.FeatureAttrRefExpr:
        if (props_FeatureAttrRefExpr == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0xb8eeb935038d48d8L, 0xae7f0c6768b8d4fcL, 0x6f0889a0c95fe67cL, 0x6f0889a0c95fe67eL, "attr", "", "");
          props_FeatureAttrRefExpr = cpb.create();
        }
        return props_FeatureAttrRefExpr;
      case LanguageConceptSwitch.FeatureRef:
        if (props_FeatureRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0xb8eeb935038d48d8L, 0xae7f0c6768b8d4fcL, 0x7b4697649917e10eL, 0x7b4697649917e10fL, "feature", "", "");
          props_FeatureRef = cpb.create();
        }
        return props_FeatureRef;
      case LanguageConceptSwitch.IConfigModelSelector:
        if (props_IConfigModelSelector == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_IConfigModelSelector = cpb.create();
        }
        return props_IConfigModelSelector;
      case LanguageConceptSwitch.RtFeatureModel:
        if (props_RtFeatureModel == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_RtFeatureModel = cpb.create();
        }
        return props_RtFeatureModel;
      case LanguageConceptSwitch.RtFeatureModelType:
        if (props_RtFeatureModelType == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("fmconfig");
          props_RtFeatureModelType = cpb.create();
        }
        return props_RtFeatureModelType;
      case LanguageConceptSwitch.StoreRtConfigStatement:
        if (props_StoreRtConfigStatement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("store config");
          props_StoreRtConfigStatement = cpb.create();
        }
        return props_StoreRtConfigStatement;
      case LanguageConceptSwitch.VarRTConfigItem:
        if (props_VarRTConfigItem == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("support variability decisions at runtime");
          cpb.rawPresentation("variability @ runtime");
          props_VarRTConfigItem = cpb.create();
        }
        return props_VarRTConfigItem;
      case LanguageConceptSwitch.VariantCase:
        if (props_VariantCase == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("case");
          props_VariantCase = cpb.create();
        }
        return props_VariantCase;
      case LanguageConceptSwitch.VariantDefault:
        if (props_VariantDefault == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("default");
          props_VariantDefault = cpb.create();
        }
        return props_VariantDefault;
      case LanguageConceptSwitch.VariantOption:
        if (props_VariantOption == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_VariantOption = cpb.create();
        }
        return props_VariantOption;
      case LanguageConceptSwitch.VariantSwitch:
        if (props_VariantSwitch == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("variant");
          props_VariantSwitch = cpb.create();
        }
        return props_VariantSwitch;
    }
    return null;
  }
}
