#!/bin/sh
#set +v

PROC_RET=0

cd tests/test.ex.cc.fm/source_gen/test/ex/cc

echo -------------------------------------
echo comptest
cd v_debug
make test
PROC_RET=$(($?+$PROC_RET))

echo -------------------------------------
echo CompWithDectab
cd ../v_production
make test
PROC_RET=$(($?+$PROC_RET))

cd ../../../../../..
cd test.ex.cc.fmrt/source_gen/test/ex/cc/fmrt/fm

echo -------------------------------------
echo test.ex.cc.fm
make test
PROC_RET=$(($?+$PROC_RET))

echo -------------------------------------
echo test.ex.cc.fm
cd ../fmrtAndComps
make test
PROC_RET=$(($?+$PROC_RET))

cd ../../../../../../../..
cd tests/test.ex.cc.var.c/source_gen/test/ex/cc/var/c/int_variant 
echo -------------------------------------
echo test.ex.cc.var.c
cd ../int_variant
make test
PROC_RET=$(($?+$PROC_RET))


echo -------------------------------------
echo test.ex.cc.var.c
cd ../float_variant
pwd
make test
PROC_RET=$(($?+$PROC_RET))


echo -------------------------------------
echo test.ex.cc.requirements.c
pwd
cd ../../../../../../../..
pwd
cd test.ex.cc.requirements.c/source_gen/test/ex/cc/requirements/c/reqc
make test
PROC_RET=$(($?+$PROC_RET))




if [ "$PROC_RET" -ne "0" ]; 
 then
    echo ""
    echo "" 
    echo "================================================"
    echo "================================================" 
    echo "               $PROC_RET test(s) failed"
    echo "================================================"
    echo "================================================"
    echo ""
    echo ""
 else
  echo ""
    echo "" 
    echo "================================================"
    echo "              OK - All tests green"
    echo "================================================"
    echo ""
    echo ""
fi

exit $PROC_RET