package com.mbeddr.core.util.pluginSolution.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.dialogs.project.newproject.MPSProjectTemplate;
import jetbrains.mps.workbench.dialogs.project.newproject.ProjectTemplatesGroup;
import javax.swing.Icon;
import org.jetbrains.annotations.Nullable;
import javax.swing.JComponent;
import jetbrains.mps.workbench.dialogs.project.newproject.TemplateFiller;

public class TemplateItem {
  private final MPSProjectTemplate myTemplate;
  private final ProjectTemplatesGroup myGroup;
  /*package*/ TemplateItem(MPSProjectTemplate template, ProjectTemplatesGroup group) {
    myTemplate = template;
    myGroup = group;
  }
  /*package*/ String getName() {
    return myTemplate.getName();
  }
  /*package*/ String getGroupName() {
    return myGroup.getName();
  }
  /*package*/ Icon getIcon() {
    return myTemplate.getIcon();
  }
  @Nullable
  /*package*/ String getDescription() {
    return myTemplate.getDescription();
  }
  @Nullable
  /*package*/ JComponent getSettings() {
    return myTemplate.getSettings();
  }
  /*package*/ TemplateFiller getTemplateFiller() {
    return myTemplate.getTemplateFiller();
  }
  /*package*/ void setNewProjectPath(String newValue) {
    myTemplate.setProjectPath(newValue);
  }
}
