package com.mbeddr.cc.requirements.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class NoEffortAssResult_SubstituteMenu extends SubstituteMenuBase {
  public NoEffortAssResult_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for NoEffortAssResult. Generated from implicit smart reference attribute.", new SNodePointer("r:eaa205a4-f15c-47d3-99e2-e648881b5997(com.mbeddr.cc.requirements.structure)", "865293814733182278")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_bhwktv_a(), CONCEPTS.NoEffortAssResult$cB));
    result.add(new SMP_Subconcepts_bhwktv_b());
    return result;
  }

  public class SMP_ReferenceScope_bhwktv_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_bhwktv_a() {
      super(CONCEPTS.NoEffortAssResult$cB, LINKS.requirement$haQv, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_bhwktv_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_bhwktv_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "NoEffortAssResult", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.NoEffortAssResult$cB);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept NoEffortAssResult$cB = MetaAdapterFactory.getConcept(0xe865cad27cc8437aL, 0x951a665bcbcb8b1aL, 0xc022423d5839546L, "com.mbeddr.cc.requirements.structure.NoEffortAssResult");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink requirement$haQv = MetaAdapterFactory.getReferenceLink(0xe865cad27cc8437aL, 0x951a665bcbcb8b1aL, 0xc022423d5839546L, 0xc022423d5839547L, "requirement");
  }
}
