package com.mbeddr.cc.requirements.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public final class SurroundWithAndFilter_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public SurroundWithAndFilter_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:a85ddf64-0248-4e9b-81ab-306845f3da69(com.mbeddr.cc.requirements.intentions)", "9294901248257401"));
  }

  @Override
  public String getPresentation() {
    return "SurroundWithAndFilter";
  }

  @Override
  public boolean isSurroundWith() {
    return true;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }

    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "REQ: " + ("Surround With AND Filter");
    }

    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      SNode and = SNodeOperations.replaceWithNewChild(node, CONCEPTS.AndFilter$g9);
      ListSequence.fromList(SLinkOperations.getChildren(and, LINKS.children$CcQw)).addElement(node);
    }

    @Override
    public boolean isApplicable(final SNode node, final EditorContext editorContext) {
      return true;
    }



    @Override
    public IntentionDescriptor getDescriptor() {
      return SurroundWithAndFilter_Intention.this;
    }

  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AndFilter$g9 = MetaAdapterFactory.getConcept(0xe865cad27cc8437aL, 0x951a665bcbcb8b1aL, 0x227d0ad6e92814c5L, "com.mbeddr.cc.requirements.structure.AndFilter");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink children$CcQw = MetaAdapterFactory.getContainmentLink(0xe865cad27cc8437aL, 0x951a665bcbcb8b1aL, 0x227d0ad6e92814c5L, 0x227d0ad6e92814c7L, "children");
  }
}
