package com.mbeddr.mpsutil.contextactions.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myInstanceCreator_CustomInstanceFunction__BehaviorDescriptor = new InstanceCreator_CustomInstanceFunction__BehaviorDescriptor();
  private final BHDescriptor myConceptInstanceIsApplicableFunction__BehaviorDescriptor = new ConceptInstanceIsApplicableFunction__BehaviorDescriptor();
  private final BHDescriptor mySideTransformSource__BehaviorDescriptor = new SideTransformSource__BehaviorDescriptor();
  private final BHDescriptor myDisableContextInstanceAction__BehaviorDescriptor = new DisableContextInstanceAction__BehaviorDescriptor();
  private final BHDescriptor myISubstituteActionBased__BehaviorDescriptor = new ISubstituteActionBased__BehaviorDescriptor();
  private final BHDescriptor mySubstituteInfoSource__BehaviorDescriptor = new SubstituteInfoSource__BehaviorDescriptor();
  private final BHDescriptor myConceptInstanceAction__BehaviorDescriptor = new ConceptInstanceAction__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myConceptInstanceAction__BehaviorDescriptor;
      case 1:
        return myConceptInstanceIsApplicableFunction__BehaviorDescriptor;
      case 2:
        return myDisableContextInstanceAction__BehaviorDescriptor;
      case 3:
        return myISubstituteActionBased__BehaviorDescriptor;
      case 4:
        return myInstanceCreator_CustomInstanceFunction__BehaviorDescriptor;
      case 5:
        return mySideTransformSource__BehaviorDescriptor;
      case 6:
        return mySubstituteInfoSource__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x677f00fb4488405eL, 0x9885abb75d472fd1L, 0x77ab0a0049e52a0cL), MetaIdFactory.conceptId(0x677f00fb4488405eL, 0x9885abb75d472fd1L, 0x839532c19a0767L), MetaIdFactory.conceptId(0x677f00fb4488405eL, 0x9885abb75d472fd1L, 0x3887a0ab996593daL), MetaIdFactory.conceptId(0x677f00fb4488405eL, 0x9885abb75d472fd1L, 0x45b23aae5585f59dL), MetaIdFactory.conceptId(0x677f00fb4488405eL, 0x9885abb75d472fd1L, 0x839532c18b11f7L), MetaIdFactory.conceptId(0x677f00fb4488405eL, 0x9885abb75d472fd1L, 0xf8736932ae2383bL), MetaIdFactory.conceptId(0x677f00fb4488405eL, 0x9885abb75d472fd1L, 0x575b1feb64e9ef51L)).seal();
}
