@startuml
title
<u>Requirement</u> UseCases.FlightJudgement.UserSuppliesFlights.UserSuppliesFlightError
<u>Scenario</u> UserSuppliesFlightError

end title
participant Pilot
url of Pilot is [[http://mbeddr.com/r:976b3005-35fa-433e-9a5d-a7c08f8308cf##__##6898387700925062299]]
participant UI
url of UI is [[http://mbeddr.com/r:976b3005-35fa-433e-9a5d-a7c08f8308cf##__##6898387700925260474]]
activate Pilot
Pilot -> UI : submitFlight(exampleFlight) [[http://mbeddr.com/r:976b3005-35fa-433e-9a5d-a7c08f8308cf##__##1942554214112319820]]
activate UI
note over UI #FFFFFF
  - maybe the database is full
  - or the connection to the database failed
end note
Pilot <-- UI:error
deactivate UI
hnote over Pilot #FFAAAA: FAILED
deactivate Pilot
@enduml
