@startuml
hide members
InFlightPoints -> PointsFactor: refines
InFlightPoints -> FasterThan100: requires also
InFlightPoints -> FasterThan200: requires also
Landing -> InFlightPoints: requires also
class InFlightPoints << (R,#DDDDDD) >> #DDDDDD {
}
url of InFlightPoints is [[http://mbeddr.com/r:0d00ad49-3316-4880-85db-33a5c3dfa97d##__##1433966787984154174]]
class FasterThan200 << (R,#DDDDDD) >> #DDDDDD {
}
url of FasterThan200 is [[http://mbeddr.com/r:0d00ad49-3316-4880-85db-33a5c3dfa97d##__##1433966787984154178]]
class FasterThan100 << (R,#DDDDDD) >> #DDDDDD {
}
url of FasterThan100 is [[http://mbeddr.com/r:0d00ad49-3316-4880-85db-33a5c3dfa97d##__##1433966787984154176]]
class PointsFactor << (R,#DDDDDD) >> #DDDDDD {
}
url of PointsFactor is [[http://mbeddr.com/r:0d00ad49-3316-4880-85db-33a5c3dfa97d##__##7451725615401720594]]
class Landing << (R,#DDDDDD) >> #DDDDDD {
}
url of Landing is [[http://mbeddr.com/r:0d00ad49-3316-4880-85db-33a5c3dfa97d##__##1433966787984154180]]
@enduml
