@startuml
hide members
InFlightPoints -> PointsFactor: refines
InFlightPoints -> FasterThan100: requires also
InFlightPoints -> FasterThan200: requires also
Landing -> InFlightPoints: requires also
class PointsFactor << (R,#DDDDDD) >> #DDDDDD {
}
url of PointsFactor is [[http://mbeddr.com/r:236197c6-7ffa-4cd1-996f-c61deb267535##__##7451725615401720594]]
class Landing << (R,#DDDDDD) >> #DDDDDD {
}
url of Landing is [[http://mbeddr.com/r:236197c6-7ffa-4cd1-996f-c61deb267535##__##1433966787984154180]]
class FasterThan200 << (R,#DDDDDD) >> #DDDDDD {
}
url of FasterThan200 is [[http://mbeddr.com/r:236197c6-7ffa-4cd1-996f-c61deb267535##__##1433966787984154178]]
class InFlightPoints << (R,#DDDDDD) >> #DDDDDD {
}
url of InFlightPoints is [[http://mbeddr.com/r:236197c6-7ffa-4cd1-996f-c61deb267535##__##1433966787984154174]]
class FasterThan100 << (R,#DDDDDD) >> #DDDDDD {
}
url of FasterThan100 is [[http://mbeddr.com/r:236197c6-7ffa-4cd1-996f-c61deb267535##__##1433966787984154176]]
@enduml
