#!/bin/sh
#set +v

PROC_RET=0

cd solutions/mbeddr.tutorial.main/source_gen/mbeddr/tutorial/main/

echo -------------------------------------
echo mbeddr tutorial - defaultExtensions
cd defaultExtensions
make test
PROC_RET=$(($?+$PROC_RET))
cd ..

echo -------------------------------------
echo mbeddr tutorial - newLanguages
cd newLanguages
make test
PROC_RET=$(($?+$PROC_RET))
cd ..



if [ "$PROC_RET" -ne "0" ]; 
 then
    echo ""
    echo "" 
    echo "================================================"
    echo "================================================" 
    echo "               $PROC_RET test(s) failed"
    echo "================================================"
    echo "================================================"
    echo ""
    echo ""
 else
  echo ""
    echo "" 
    echo "================================================"
    echo "              OK - All tests green"
    echo "================================================"
    echo ""
    echo ""
fi

exit $PROC_RET