package com.mbeddr.core.embedded.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import com.mbeddr.core.embedded.behavior.IRegisterAccess__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import com.mbeddr.core.embedded.behavior.Register__BehaviorDescriptor;
import jetbrains.mps.typesystem.inference.EquationInfo;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.builder.SNodeBuilder;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class typeof_HalfRegExpr_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_HalfRegExpr_InferenceRule() {
  }
  public void applyRule(final SNode hre, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    SNode type;
    SNode register = IRegisterAccess__BehaviorDescriptor.register_id5W7baq$5NAe.invoke(hre);
    if (SPropertyOperations.getBoolean(register, PROPS.signed$rNTM)) {
      type = ((int) Register__BehaviorDescriptor.getBitCount_id30ICD1Hyq_w.invoke(register) == 16 ? createInt8tType_lvy6an_a0a0a2a1() : createInt16tType_lvy6an_a0a0a2a1());
    } else {
      type = ((int) Register__BehaviorDescriptor.getBitCount_id30ICD1Hyq_w.invoke(register) == 16 ? createUnsignedInt8tType_lvy6an_a0a0a0c0b() : createUnsignedInt16tType_lvy6an_a0a0a0c0b());
    }
    SPropertyOperations.assign(type, PROPS.volatile$hJNe, true);
    {
      SNode _nodeToCheck_1029348928467 = hre;
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:5e0c701a-52e5-4f8d-a7a8-9a9d532f99cc(com.mbeddr.core.embedded.typesystem)", "6847490852669359476", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:5e0c701a-52e5-4f8d-a7a8-9a9d532f99cc(com.mbeddr.core.embedded.typesystem)", "6847490852669359478", true), (SNode) type, _info_12389875345);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.HalfRegisterRefExpr$XI;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }
  private static SNode createInt8tType_lvy6an_a0a0a2a1() {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.Int8tType$tq);
    return n0.getResult();
  }
  private static SNode createInt16tType_lvy6an_a0a0a2a1() {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.Int16tType$FW);
    return n0.getResult();
  }
  private static SNode createUnsignedInt8tType_lvy6an_a0a0a0c0b() {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.UnsignedInt8tType$n3);
    return n0.getResult();
  }
  private static SNode createUnsignedInt16tType_lvy6an_a0a0a0c0b() {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.UnsignedInt16tType$pu);
    return n0.getResult();
  }

  private static final class PROPS {
    /*package*/ static final SProperty signed$rNTM = MetaAdapterFactory.getProperty(0x783af01f87a7412cL, 0xbe99293a162652b5L, 0x5f072ca6a41506a2L, 0x5f072ca6a41506a3L, "signed");
    /*package*/ static final SProperty volatile$hJNe = MetaAdapterFactory.getProperty(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x7af69e2e83a1ba36L, 0x28d183d9a4fae02fL, "volatile");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept HalfRegisterRefExpr$XI = MetaAdapterFactory.getConcept(0x783af01f87a7412cL, 0xbe99293a162652b5L, 0x5f072ca6a4180547L, "com.mbeddr.core.embedded.structure.HalfRegisterRefExpr");
    /*package*/ static final SConcept Int8tType$tq = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x75739ed9f39e387aL, "com.mbeddr.core.expressions.structure.Int8tType");
    /*package*/ static final SConcept Int16tType$FW = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x75739ed9f39e3883L, "com.mbeddr.core.expressions.structure.Int16tType");
    /*package*/ static final SConcept UnsignedInt8tType$n3 = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x75739ed9f39e389dL, "com.mbeddr.core.expressions.structure.UnsignedInt8tType");
    /*package*/ static final SConcept UnsignedInt16tType$pu = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x75739ed9f39e38a2L, "com.mbeddr.core.expressions.structure.UnsignedInt16tType");
  }
}
