package com.mbeddr.core.base.pluginSolution.plugin;

/*Generated by MPS */

import com.intellij.openapi.actionSystem.ToggleAction;
import com.intellij.icons.AllIcons;
import org.jetbrains.annotations.NotNull;
import com.intellij.openapi.actionSystem.AnActionEvent;
import jetbrains.mps.plugins.projectplugins.ProjectPluginManager;
import javax.swing.JComponent;
import com.intellij.openapi.project.Project;

public class ApproximateSearchToggleAction extends ToggleAction {


  public ApproximateSearchToggleAction() {
    super("Approximate Search", "Search with an allowed error distance of " + SearchEngine.MEDIUM_SEARCH_TOLERANCE, AllIcons.Nodes.Undeploy);
  }

  @Override
  public boolean isSelected(@NotNull AnActionEvent event) {
    SearchViewer viewer = (SearchViewer) check_852tkz_a0a0a4(ProjectPluginManager.getInstance(event.getProject()).getTool(MbeddrSearchViewer_Tool.class));
    return check_852tkz_a1a4(viewer);
  }

  @Override
  public void setSelected(@NotNull AnActionEvent event, boolean flag) {
    SearchViewer viewer = (SearchViewer) check_852tkz_a0a0a6(ProjectPluginManager.getInstance(check_852tkz_a0a0a0a0g(event)).getTool(MbeddrSearchViewer_Tool.class));
    check_852tkz_a1a6(viewer, flag);
  }
  private static JComponent check_852tkz_a0a0a4(MbeddrSearchViewer_Tool checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getComponent();
    }
    return null;
  }
  private static boolean check_852tkz_a1a4(SearchViewer checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.isApproximateSearch();
    }
    return false;
  }
  private static JComponent check_852tkz_a0a0a6(MbeddrSearchViewer_Tool checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getComponent();
    }
    return null;
  }
  private static Project check_852tkz_a0a0a0a0g(AnActionEvent checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getProject();
    }
    return null;
  }
  private static void check_852tkz_a1a6(SearchViewer checkedDotOperand, Boolean flag) {
    if (null != checkedDotOperand) {
      checkedDotOperand.toggleApproximateSearch(flag);
    }

  }
}
