package com.mbeddr.mpsutil.wizard.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class CreateWizardExpressionBase_SubstituteMenu extends SubstituteMenuBase {
  public CreateWizardExpressionBase_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for CreateWizardExpressionBase. Generated from implicit smart reference attribute.", new SNodePointer("r:2ffefd76-4fe0-43c2-9fbd-203c67a47b34(com.mbeddr.mpsutil.wizard.structure)", "7775334123752824719")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_6loap0_a(), CONCEPTS.CreateWizardExpressionBase$Io));
    result.add(new SMP_Subconcepts_6loap0_b());
    return result;
  }

  public class SMP_ReferenceScope_6loap0_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_6loap0_a() {
      super(CONCEPTS.CreateWizardExpressionBase$Io, LINKS.wizard$_LxC, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_6loap0_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_6loap0_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "CreateWizardExpressionBase", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.CreateWizardExpressionBase$Io);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept CreateWizardExpressionBase$Io = MetaAdapterFactory.getConcept(0x306d745629e24ea3L, 0x9c46e7b830b08481L, 0x6be78930a8429f8fL, "com.mbeddr.mpsutil.wizard.structure.CreateWizardExpressionBase");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink wizard$_LxC = MetaAdapterFactory.getReferenceLink(0x306d745629e24ea3L, 0x9c46e7b830b08481L, 0x6be78930a8429f8fL, 0x6be78930a8429fa5L, "wizard");
  }
}
