package com.mbeddr.cc.var.composition.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import org.jetbrains.mps.openapi.model.SReference;
import jetbrains.mps.internal.collections.runtime.Sequence;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;

public final class CompositionStrategy__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x21ac77a41b6644c5L, 0xaaec94e43bb86519L, 0x3fa2b6b6b41954e7L, "com.mbeddr.cc.var.composition.structure.CompositionStrategy");

  public static final SMethod<CompositionResult> compose_id3YyHFqO7EVE = new SMethodBuilder<CompositionResult>(new SJavaCompoundTypeImpl(CompositionResult.class)).name("compose").modifiers(12, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4585428266438799082L).languageId(0xaaec94e43bb86519L, 0x21ac77a41b6644c5L).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""), SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""), SMethodBuilder.createJavaParameter(CompositionContext.class, ""));
  public static final SMethod<Void> removeCompositionStuff_id3YyHFqO8Kht = new SMethodBuilder<Void>(new SJavaCompoundTypeImpl(Void.class)).name("removeCompositionStuff").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4585428266439083101L).languageId(0xaaec94e43bb86519L, 0x21ac77a41b6644c5L).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));
  public static final SMethod<Void> replaceReferences_id3YyHFqO98RF = new SMethodBuilder<Void>(new SJavaCompoundTypeImpl(Void.class)).name("replaceReferences").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4585428266439183851L).languageId(0xaaec94e43bb86519L, 0x21ac77a41b6644c5L).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""), SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""), SMethodBuilder.createJavaParameter((Class<SModel>) ((Class) Object.class), ""));

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(compose_id3YyHFqO7EVE, removeCompositionStuff_id3YyHFqO8Kht, replaceReferences_id3YyHFqO98RF);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static void removeCompositionStuff_id3YyHFqO8Kht(@NotNull SNode __thisNode__, SNode n) {
    ListSequence.fromList(SNodeOperations.getNodeDescendants(n, CONCEPTS.ICompositionControl$3A, false, new SAbstractConcept[]{})).visitAll((it) -> SNodeOperations.deleteNode(it));
  }
  /*package*/ static void replaceReferences_id3YyHFqO98RF(@NotNull SNode __thisNode__, SNode originalTarget, SNode newTarget, SModel m) {
    for (SNode n : ListSequence.fromList(SModelOperations.nodes(m, null))) {
      Iterable<? extends SReference> references = n.getReferences();
      for (SReference r : Sequence.fromIterable(references)) {
        if (r.getTargetNode() == originalTarget) {
          SReferenceLink role = r.getLink();
          n.setReferenceTarget(role, newTarget);
        }
      }
    }
  }

  /*package*/ CompositionStrategy__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 1:
        removeCompositionStuff_id3YyHFqO8Kht(node, (SNode) parameters[0]);
        return null;
      case 2:
        replaceReferences_id3YyHFqO98RF(node, (SNode) parameters[0], (SNode) parameters[1], (SModel) parameters[2]);
        return null;
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept ICompositionControl$3A = MetaAdapterFactory.getInterfaceConcept(0x21ac77a41b6644c5L, 0xaaec94e43bb86519L, 0x3fa2b6b6b4238999L, "com.mbeddr.cc.var.composition.structure.ICompositionControl");
  }
}
