package com.mbeddr.mpsutil.json.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptArray = createDescriptorForArray();
  /*package*/ final ConceptDescriptor myConceptBoolean = createDescriptorForBoolean();
  /*package*/ final ConceptDescriptor myConceptIValue = createDescriptorForIValue();
  /*package*/ final ConceptDescriptor myConceptJSONObject = createDescriptorForJSONObject();
  /*package*/ final ConceptDescriptor myConceptJsonFile = createDescriptorForJsonFile();
  /*package*/ final ConceptDescriptor myConceptNull = createDescriptorForNull();
  /*package*/ final ConceptDescriptor myConceptNumber = createDescriptorForNumber();
  /*package*/ final ConceptDescriptor myConceptString = createDescriptorForString();
  /*package*/ final ConceptDescriptor myConceptVariable = createDescriptorForVariable();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptArray, myConceptBoolean, myConceptIValue, myConceptJSONObject, myConceptJsonFile, myConceptNull, myConceptNumber, myConceptString, myConceptVariable);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Array:
        return myConceptArray;
      case LanguageConceptSwitch.Boolean:
        return myConceptBoolean;
      case LanguageConceptSwitch.IValue:
        return myConceptIValue;
      case LanguageConceptSwitch.JSONObject:
        return myConceptJSONObject;
      case LanguageConceptSwitch.JsonFile:
        return myConceptJsonFile;
      case LanguageConceptSwitch.Null:
        return myConceptNull;
      case LanguageConceptSwitch.Number:
        return myConceptNumber;
      case LanguageConceptSwitch.String:
        return myConceptString;
      case LanguageConceptSwitch.Variable:
        return myConceptVariable;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForArray() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.mbeddr.mpsutil.json", "Array", 0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d5efL);
    b.class_(false, false, false);
    b.parent(0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d5e7L);
    b.origin("r:be665d13-1e1d-44cd-9817-8bd4d610f422(com.mbeddr.mpsutil.json.structure)/4342692121161029103");
    b.version(3);
    b.aggregate("values", 0x3c445779c2b0d5f2L).target(0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d5e7L).optional(true).ordered(true).multiple(true).origin("4342692121161029106").done();
    b.alias("[");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBoolean() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.mbeddr.mpsutil.json", "Boolean", 0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d5eaL);
    b.class_(false, false, false);
    b.parent(0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d5e7L);
    b.origin("r:be665d13-1e1d-44cd-9817-8bd4d610f422(com.mbeddr.mpsutil.json.structure)/4342692121161029098");
    b.version(3);
    b.property("value", 0x3c445779c2b0d5edL).type(PrimitiveTypeId.BOOLEAN).origin("4342692121161029101").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.mbeddr.mpsutil.json", "IValue", 0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d5e7L);
    b.interface_();
    b.origin("r:be665d13-1e1d-44cd-9817-8bd4d610f422(com.mbeddr.mpsutil.json.structure)/4342692121161029095");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForJSONObject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.mbeddr.mpsutil.json", "JSONObject", 0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d576L);
    b.class_(false, false, false);
    b.parent(0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d5e7L);
    b.origin("r:be665d13-1e1d-44cd-9817-8bd4d610f422(com.mbeddr.mpsutil.json.structure)/4342692121161028982");
    b.version(3);
    b.aggregate("variables", 0x3c445779c2b0d6c9L).target(0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d577L).optional(true).ordered(true).multiple(true).origin("4342692121161029321").done();
    b.alias("{");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForJsonFile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.mbeddr.mpsutil.json", "JsonFile", 0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b1d3e3L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:be665d13-1e1d-44cd-9817-8bd4d610f422(com.mbeddr.mpsutil.json.structure)/4342692121161094115");
    b.version(3);
    b.property("folder", 0x31241275c648240bL).type(PrimitiveTypeId.STRING).origin("3540975504067142667").done();
    b.aggregate("object", 0x3c445779c2b1d3feL).target(0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d5e7L).optional(false).ordered(true).multiple(false).origin("4342692121161094142").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNull() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.mbeddr.mpsutil.json", "Null", 0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d6d7L);
    b.class_(false, false, false);
    b.parent(0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d5e7L);
    b.origin("r:be665d13-1e1d-44cd-9817-8bd4d610f422(com.mbeddr.mpsutil.json.structure)/4342692121161029335");
    b.version(3);
    b.alias("null");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNumber() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.mbeddr.mpsutil.json", "Number", 0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d6d0L);
    b.class_(false, false, false);
    b.parent(0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d5e7L);
    b.origin("r:be665d13-1e1d-44cd-9817-8bd4d610f422(com.mbeddr.mpsutil.json.structure)/4342692121161029328");
    b.version(3);
    b.property("value", 0x6a20681bcbe39851L).type(PrimitiveTypeId.STRING).origin("7647226635869198417").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForString() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.mbeddr.mpsutil.json", "String", 0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d6cbL);
    b.class_(false, false, false);
    b.parent(0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d5e7L);
    b.origin("r:be665d13-1e1d-44cd-9817-8bd4d610f422(com.mbeddr.mpsutil.json.structure)/4342692121161029323");
    b.version(3);
    b.property("value", 0x3c445779c2b0d6ceL).type(PrimitiveTypeId.STRING).origin("4342692121161029326").done();
    b.alias("\"");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForVariable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.mbeddr.mpsutil.json", "Variable", 0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d577L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:be665d13-1e1d-44cd-9817-8bd4d610f422(com.mbeddr.mpsutil.json.structure)/4342692121161028983");
    b.version(3);
    b.aggregate("value", 0x3c445779c2b0d5e8L).target(0xb5c0bb04c5834b2aL, 0xa66e1eab92d33c68L, 0x3c445779c2b0d5e7L).optional(false).ordered(true).multiple(false).origin("4342692121161029096").done();
    b.alias("\"");
    return b.create();
  }
}
