package com.mbeddr.ext.components.statemachine.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import com.mbeddr.ext.components.behavior.Component__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class check_ProvidedOperationBinding_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_ProvidedOperationBinding_NonTypesystemRule() {
  }
  public void applyRule(final SNode providedOperationBinding, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    final SNode machine = SNodeOperations.getNodeAncestor(providedOperationBinding, CONCEPTS.Statemachine$h1, false, false);
    if (Sequence.fromIterable(Component__BehaviorDescriptor.fields_id6JVEnxIj2nQ.invoke(SNodeOperations.getNodeAncestor(providedOperationBinding, CONCEPTS.Component$va, false, false))).where((it) -> {
      SNode type = SLinkOperations.getTarget(it, LINKS.type$sXU3);
      return SNodeOperations.isInstanceOf(type, CONCEPTS.StatemachineType$wP) && SLinkOperations.getTarget(SNodeOperations.cast(type, CONCEPTS.StatemachineType$wP), LINKS.machine$eifp) == machine;
    }).count() != 1) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(providedOperationBinding, "exactly one instance of the statemachine is expected in this component", "r:9eccd3a7-30d5-445b-9861-4a612ecc56b6(com.mbeddr.ext.components.statemachine.typesystem)", "4514118643329825014", null, errorTarget);
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.ProvidedOperationBinding$bL;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Statemachine$h1 = MetaAdapterFactory.getConcept(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x50315072219db271L, "com.mbeddr.ext.statemachines.structure.Statemachine");
    /*package*/ static final SConcept Component$va = MetaAdapterFactory.getConcept(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x3e5659cd94a235c9L, "com.mbeddr.ext.components.structure.Component");
    /*package*/ static final SConcept StatemachineType$wP = MetaAdapterFactory.getConcept(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x6cf6e22eb96bd531L, "com.mbeddr.ext.statemachines.structure.StatemachineType");
    /*package*/ static final SConcept ProvidedOperationBinding$bL = MetaAdapterFactory.getConcept(0x13a36f9083c54bf6L, 0x9dd670e455f1ef36L, 0x3ea55efd41187917L, "com.mbeddr.ext.components.statemachine.structure.ProvidedOperationBinding");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink type$sXU3 = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x46a2a92ac61b183L, 0x46a2a92ac61b184L, "type");
    /*package*/ static final SReferenceLink machine$eifp = MetaAdapterFactory.getReferenceLink(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x6cf6e22eb96bd531L, 0x6cf6e22eb96bd532L, "machine");
  }
}
