package com.mbeddr.core.base.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import jetbrains.mps.scope.Scope;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.scopes.runtime.NamedElementsScope;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.internal.collections.runtime.Sequence;
import java.util.Objects;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.util.Collections;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public final class IVisibleElementProvider__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getInterfaceConcept(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x6315bcc6eff580a3L, "com.mbeddr.core.base.structure.IVisibleElementProvider");

  public static final SMethod<Iterable<SNode>> visibleContentsOfType_id6clJcrJXo2_ = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("visibleContentsOfType").modifiers(12, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7139820346881179813L).languageId(0xaa41d1b2bffa7eb1L, 0xd4280a54f6df4383L).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));
  public static final SMethod<Scope> visibleContentsOfType_id79$zShlSHxZ = new SMethodBuilder<Scope>(new SJavaCompoundTypeImpl(Scope.class)).name("visibleContentsOfType").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(8242871016534235263L).languageId(0xaa41d1b2bffa7eb1L, 0xd4280a54f6df4383L).build2(SMethodBuilder.createJavaParameter((Class<SAbstractConcept>) ((Class) Object.class), ""));
  public static final SMethod<Boolean> hasVisibleContentsOfType_id7Vd878lThb_ = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("hasVisibleContentsOfType").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(9136994893370299109L).languageId(0xaa41d1b2bffa7eb1L, 0xd4280a54f6df4383L).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));
  public static final SMethod<Boolean> hasVisibleContentsOfType_idjS_CvxKV1a = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("hasVisibleContentsOfType").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(358201680728404042L).languageId(0xaa41d1b2bffa7eb1L, 0xd4280a54f6df4383L).build2(SMethodBuilder.createJavaParameter((Class<SAbstractConcept>) ((Class) Object.class), ""));
  public static final SMethod<SNode> findByName_id6clJcrJXo2G = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("findByName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7139820346881179820L).languageId(0xaa41d1b2bffa7eb1L, 0xd4280a54f6df4383L).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""), SMethodBuilder.createJavaParameter(String.class, ""));
  public static final SMethod<SNode> findByName_idjS_CvxKV3X = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("findByName").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(358201680728404221L).languageId(0xaa41d1b2bffa7eb1L, 0xd4280a54f6df4383L).build2(SMethodBuilder.createJavaParameter((Class<SAbstractConcept>) ((Class) Object.class), ""), SMethodBuilder.createJavaParameter(String.class, ""));
  public static final SMethod<Iterable<SNode>> visibleContentsOfTypeAsSequence_id3g6LnlWuSo8 = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("visibleContentsOfTypeAsSequence").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3748900848222832136L).languageId(0xaa41d1b2bffa7eb1L, 0xd4280a54f6df4383L).build2(SMethodBuilder.createJavaParameter((Class<SAbstractConcept>) ((Class) Object.class), ""));

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(visibleContentsOfType_id6clJcrJXo2_, visibleContentsOfType_id79$zShlSHxZ, hasVisibleContentsOfType_id7Vd878lThb_, hasVisibleContentsOfType_idjS_CvxKV1a, findByName_id6clJcrJXo2G, findByName_idjS_CvxKV3X, visibleContentsOfTypeAsSequence_id3g6LnlWuSo8);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static Scope visibleContentsOfType_id79$zShlSHxZ(@NotNull SNode __thisNode__, SAbstractConcept targetConcept) {
    Iterable<SNode> visibleContentsOfType = IVisibleElementProvider__BehaviorDescriptor.visibleContentsOfType_id6clJcrJXo2_.invoke(__thisNode__, SNodeOperations.asNode(targetConcept));
    // NamedElementsScope might perform slightly better
    if (SConceptOperations.isSubConceptOf(SNodeOperations.asSConcept(targetConcept), CONCEPTS.INamedConcept$Kd)) {
      return new NamedElementsScope(SNodeOperations.ofConcept(visibleContentsOfType, CONCEPTS.INamedConcept$Kd));
    } else {
      return ListScope.forResolvableElements(visibleContentsOfType);
    }
  }
  @Deprecated
  /*package*/ static boolean hasVisibleContentsOfType_id7Vd878lThb_(@NotNull SNode __thisNode__, SNode targetConcept) {
    return ((boolean) IVisibleElementProvider__BehaviorDescriptor.hasVisibleContentsOfType_idjS_CvxKV1a.invoke(__thisNode__, SNodeOperations.asSConcept(targetConcept)));
  }
  /*package*/ static boolean hasVisibleContentsOfType_idjS_CvxKV1a(@NotNull SNode __thisNode__, SAbstractConcept targetConcept) {
    return Sequence.fromIterable(IVisibleElementProvider__BehaviorDescriptor.visibleContentsOfTypeAsSequence_id3g6LnlWuSo8.invoke(__thisNode__, targetConcept)).isNotEmpty();
  }
  @Deprecated
  /*package*/ static SNode findByName_id6clJcrJXo2G(@NotNull SNode __thisNode__, SNode targetConcept, String name) {
    return ((SNode) IVisibleElementProvider__BehaviorDescriptor.findByName_idjS_CvxKV3X.invoke(__thisNode__, SNodeOperations.asSConcept(targetConcept), name));
  }
  /*package*/ static SNode findByName_idjS_CvxKV3X(@NotNull SNode __thisNode__, SAbstractConcept targetConcept, final String name) {
    if (!(SConceptOperations.isSubConceptOf(SNodeOperations.asSConcept(targetConcept), CONCEPTS.INamedConcept$Kd))) {
      throw new IllegalArgumentException("targetConcept must implement INamedConcept");
    }

    return Sequence.fromIterable(SNodeOperations.ofConcept(IVisibleElementProvider__BehaviorDescriptor.visibleContentsOfTypeAsSequence_id3g6LnlWuSo8.invoke(__thisNode__, targetConcept), CONCEPTS.INamedConcept$Kd)).findFirst((it) -> Objects.equals(SPropertyOperations.getString(it, PROPS.name$MnvL), name));
  }
  /*package*/ static Iterable<SNode> visibleContentsOfTypeAsSequence_id3g6LnlWuSo8(@NotNull SNode __thisNode__, SAbstractConcept targetConcept) {
    Scope visibleContentsOfType = IVisibleElementProvider__BehaviorDescriptor.visibleContentsOfType_id79$zShlSHxZ.invoke(__thisNode__, targetConcept);

    // no NPE for null scopes
    if (visibleContentsOfType == null) {
      return Sequence.fromIterable(Collections.<SNode>emptyList());
    }

    return visibleContentsOfType.getAvailableElements(null);
  }

  /*package*/ IVisibleElementProvider__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 1:
        return (T) ((Scope) visibleContentsOfType_id79$zShlSHxZ(node, (SAbstractConcept) parameters[0]));
      case 2:
        return (T) ((Boolean) hasVisibleContentsOfType_id7Vd878lThb_(node, (SNode) parameters[0]));
      case 3:
        return (T) ((Boolean) hasVisibleContentsOfType_idjS_CvxKV1a(node, (SAbstractConcept) parameters[0]));
      case 4:
        return (T) ((SNode) findByName_id6clJcrJXo2G(node, (SNode) parameters[0], (String) parameters[1]));
      case 5:
        return (T) ((SNode) findByName_idjS_CvxKV3X(node, (SAbstractConcept) parameters[0], (String) parameters[1]));
      case 6:
        return (T) ((Iterable<SNode>) visibleContentsOfTypeAsSequence_id3g6LnlWuSo8(node, (SAbstractConcept) parameters[0]));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept INamedConcept$Kd = MetaAdapterFactory.getInterfaceConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, "jetbrains.mps.lang.core.structure.INamedConcept");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
