package com.mbeddr.core.base.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_Deprecated_ListOfModelsScope_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_Deprecated_ListOfModelsScope_NonTypesystemRule() {
  }
  public void applyRule(final SNode listOfModelsScope, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    ListSequence.fromList(SLinkOperations.getChildren(listOfModelsScope, LINKS.models_old$thV3)).visitAll((it) -> {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(it, "This property is deprecated. Please use the new property or execute rerunnable migrations", "r:1b0f275e-bd62-4f6e-8c4b-51b05d651a63(com.mbeddr.core.base.typesystem)", "1340476885415985903", null, errorTarget);
      }
    });
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.ListOfModelsScope$y;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink models_old$thV3 = MetaAdapterFactory.getContainmentLink(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x4f3a022259f10d65L, 0x4f3a022259f10ecaL, "models_old");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ListOfModelsScope$y = MetaAdapterFactory.getConcept(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x4f3a022259f10d65L, "com.mbeddr.core.base.structure.ListOfModelsScope");
  }
}
