package com.mbeddr.mpsutil.toolrunner;

/*Generated by MPS */

import java.util.List;

/**
 * Interface to check the availability of external tools and their proper configuration.
 */
public interface ToolsAvailabilityChecker {

  /**
   * Returns the name of the category of tools that this checker checks (e.g. cbmc).
   */
  String categoryName();

  /**
   * Returns a string with the result of the availability check.
   */
  boolean checkAvailability(List<String> messages);

}
