package com.mbeddr.mpsutil.dependenciesdiagram.editor;

/*Generated by MPS */

import java.awt.Color;

public class ColorsUsedInMps {
  public static final Color ASPECT_ACTION = new Color(252, 176, 167);
  public static final Color ASPECT_BEHAVIOR = new Color(243, 191, 125);
  public static final Color ASPECT_CONSTRAINT = new Color(149, 209, 243);
  public static final Color ASPECT_DATAFLOW = new Color(152, 205, 236);
  public static final Color ASPECT_EDITOR = new Color(237, 221, 134);
  public static final Color ASPECT_REFACTORING = new Color(182, 149, 200);
  public static final Color ASPECT_STRUCTURE = new Color(159, 234, 164);
  public static final Color ASPECT_TEXTGEN = new Color(141, 228, 208);
  public static final Color ASPECT_TYPE = new Color(219, 182, 255);
  public static final Color ASPECT_USAGESFINDER = new Color(161, 184, 197);

  public static final Color MODULE_DEVKIT = new Color(165, 216, 245);
  public static final Color MODULE_GENERATOR = new Color(183, 208, 218);
  public static final Color MODULE_LANGUAGE = new Color(238, 224, 144);
  public static final Color MODULE_SOLUTION = new Color(238, 187, 119);

  public static final Color MODEL_MODEL = new Color(194, 157, 230);
  public static final Color MODEL_TRANSIENT = new Color(191, 154, 228);
  public static final Color MODEL_TEMPLATES = new Color(157, 182, 216);

  public static final Color reduction = new Color(174, 202, 212);
  public static final Color rule = new Color(217, 180, 255);
}
