<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecorepackage" nsURI="www.itemis.de">
  <eClassifiers xsi:type="ecore:EEnum" name="simpleEnum">
    <eLiterals name="val1" value="1"/>
    <eLiterals name="val2" value="2"/>
    <eLiterals name="val3" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="testClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attr1" eType="#//simpleEnum"/>
  </eClassifiers>
</ecore:EPackage>
