package com.mbeddr.mpsutil.interpreter.plugin.plugin;

/*Generated by MPS */

import com.intellij.openapi.actionSystem.ToggleAction;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.mbeddr.mpsutil.interpreter.rt.InterpreterEvaluationHelper;

public class CacheInterpreter extends ToggleAction {

  public CacheInterpreter() {
    super("Enable Interpreter Cache");
  }

  @Override
  public boolean isSelected(AnActionEvent event) {
    return InterpreterEvaluationHelper.isCachingEnabled();
  }
  @Override
  public void setSelected(AnActionEvent event, boolean b) {
    InterpreterEvaluationHelper.setCachingEnabled(b);

  }
}
