package com.mbeddr.core.util.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class ClosureParameterRef_SubstituteMenu extends SubstituteMenuBase {
  public ClosureParameterRef_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for ClosureParameterRef. Generated from implicit smart reference attribute.", new SNodePointer("r:5209fc71-bade-45c9-9079-f2d474f0d6ca(com.mbeddr.core.util.structure)", "8257817273846948862")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_6bflux_a(), CONCEPTS.ClosureParameterRef$8e));
    result.add(new SMP_Subconcepts_6bflux_b());
    return result;
  }

  public class SMP_ReferenceScope_6bflux_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_6bflux_a() {
      super(CONCEPTS.ClosureParameterRef$8e, LINKS.param$DneM, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_6bflux_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_6bflux_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "ClosureParameterRef", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.ClosureParameterRef$8e);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ClosureParameterRef$8e = MetaAdapterFactory.getConcept(0x2693fc719b0e4b05L, 0xab13f57227d675f2L, 0x7299a90f0bbb63feL, "com.mbeddr.core.util.structure.ClosureParameterRef");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink param$DneM = MetaAdapterFactory.getReferenceLink(0x2693fc719b0e4b05L, 0xab13f57227d675f2L, 0x7299a90f0bbb63feL, 0x7299a90f0bbb63ffL, "param");
  }
}
