package com.mbeddr.core.util.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;

public class ErrorTypeNotFound_SubstituteMenu extends SubstituteMenuBase {
  public ErrorTypeNotFound_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for " + "ErrorTypeNotFound", new SNodePointer("r:2003a7dc-1d33-4109-abf0-90ad1f9028fd(com.mbeddr.core.util.editor)", "2531002643696488362")));
  }

}
