package com.mbeddr.doc.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;

public class Invisible_SubstituteMenu extends SubstituteMenuBase {
  public Invisible_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for " + "Invisible", new SNodePointer("r:6b7eb85f-64d8-4de6-8906-0e18804729df(com.mbeddr.doc.editor)", "3619610929683239244")));
  }

}
