# NOTICE: this Makefile has been generated, so your
#         modifications may get lost. To rebuild this
#         file, run the './configure' script.

# The application's name.
APPL=Generic_ECU

# The include and source paths.
IPATH=. inc-gen inc
VPATH=. src-gen src

# Include the common make definitions.
include Makedefs

# The object file rules of this application.
${BPATH}/${APPL}.run: ${BPATH}/right_Bundle_Branch_ID_638.o
${BPATH}/${APPL}.run: ${BPATH}/CrossTalk_ID_5691.o
${BPATH}/${APPL}.run: ${BPATH}/system.o
${BPATH}/${APPL}.run: ${BPATH}/io.o
${BPATH}/${APPL}.run: ${BPATH}/right_ventricular_myocardium_ID_754.o
${BPATH}/${APPL}.run: ${BPATH}/left_Bundle_Branch_ID_667.o
${BPATH}/${APPL}.run: ${BPATH}/left_ventricular_myocardium_ID_812.o
${BPATH}/${APPL}.run: ${BPATH}/gen_random_ID_5738.o
${BPATH}/${APPL}.run: ${BPATH}/atrial_myocardium_ID_524.o
${BPATH}/${APPL}.run: ${BPATH}/Bundle_of_His_ID_580.o
${BPATH}/${APPL}.run: ${BPATH}/right_Purkinje_Fibers_ID_696.o
${BPATH}/${APPL}.run: ${BPATH}/left_Purkinje_Fibers_ID_725.o
${BPATH}/${APPL}.run: ${BPATH}/AV_Node_ID_549.o
${BPATH}/${APPL}.run: ${BPATH}/data_dictionary.o
${BPATH}/${APPL}.run: ${BPATH}/r_wave_ID_934.o
${BPATH}/${APPL}.run: ${BPATH}/Heart_ID_88.o
${BPATH}/${APPL}.run: ${BPATH}/p_wave_ID_906.o
${BPATH}/${APPL}.run: ${BPATH}/SA_Node_ID_455.o
