package com.mbeddr.doc.qa.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptConceptsDocumentationAssessment = createDescriptorForConceptsDocumentationAssessment();
  /*package*/ final ConceptDescriptor myConceptRulesDocumentationAssessment = createDescriptorForRulesDocumentationAssessment();
  /*package*/ final ConceptDescriptor myConceptSpecificationAssessmentResult = createDescriptorForSpecificationAssessmentResult();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xc8e0d19c3cf4b31L, 0xaf77531227edbce8L, "com.mbeddr.core.qa");
    deps.extendedLanguage(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, "com.mbeddr.core.base");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptConceptsDocumentationAssessment, myConceptRulesDocumentationAssessment, myConceptSpecificationAssessmentResult);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ConceptsDocumentationAssessment:
        return myConceptConceptsDocumentationAssessment;
      case LanguageConceptSwitch.RulesDocumentationAssessment:
        return myConceptRulesDocumentationAssessment;
      case LanguageConceptSwitch.SpecificationAssessmentResult:
        return myConceptSpecificationAssessmentResult;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForConceptsDocumentationAssessment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.mbeddr.doc.qa", "ConceptsDocumentationAssessment", 0x5344b78122424d23L, 0xbe90673ee10bea46L, 0x15b95a4d5ec1292L);
    b.class_(false, false, false);
    // extends: com.mbeddr.core.qa.structure.AbstractStructureCoverageAssessment
    b.super_(0xc8e0d19c3cf4b31L, 0xaf77531227edbce8L, 0x15b95a4d5d119aeL);
    b.origin("r:d1c76b51-b992-43d8-94f8-013d38773d9f(com.mbeddr.doc.qa.structure)/97836352114791058");
    b.version(3);
    b.alias("concepts not documented");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRulesDocumentationAssessment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.mbeddr.doc.qa", "RulesDocumentationAssessment", 0x5344b78122424d23L, 0xbe90673ee10bea46L, 0x15b95a4d5eef278L);
    b.class_(false, false, false);
    // extends: com.mbeddr.core.qa.structure.AbstractStructureCoverageAssessment
    b.super_(0xc8e0d19c3cf4b31L, 0xaf77531227edbce8L, 0x15b95a4d5d119aeL);
    b.origin("r:d1c76b51-b992-43d8-94f8-013d38773d9f(com.mbeddr.doc.qa.structure)/97836352114979448");
    b.version(3);
    b.alias("rules not documented");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSpecificationAssessmentResult() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.mbeddr.doc.qa", "SpecificationAssessmentResult", 0x5344b78122424d23L, 0xbe90673ee10bea46L, 0x15b95a4d5eea883L);
    b.class_(false, false, false);
    // extends: com.mbeddr.core.base.structure.AssessmentResult
    b.super_(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0xc022423d582d809L);
    b.origin("r:d1c76b51-b992-43d8-94f8-013d38773d9f(com.mbeddr.doc.qa.structure)/97836352114960515");
    b.version(3);
    b.associate("elem", 0x15b95a4d5eea884L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L).optional(false).origin("97836352114960516").done();
    return b.create();
  }
}
