package com.mbeddr.doc.gen_xhtml.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintFunction;
import jetbrains.mps.smodel.runtime.ConstraintContext_CanBeRoot;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.generator.TransientModelsModule;
import jetbrains.mps.smodel.SModelStereotype;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class XHTMLFile_Constraints extends BaseConstraintsDescriptor {
  public XHTMLFile_Constraints() {
    super(CONCEPTS.XHTMLFile$D0);
  }

  @Override
  public ConstraintFunction<ConstraintContext_CanBeRoot, Boolean> calculateCanBeRootConstraint() {
    return new ConstraintFunction<ConstraintContext_CanBeRoot, Boolean>() {
      @NotNull
      public Boolean invoke(@NotNull ConstraintContext_CanBeRoot context, @Nullable CheckingNodeContext checkingNodeContext) {
        boolean result = staticCanBeARoot(context.getModel());

        if (!(result) && checkingNodeContext != null) {
          checkingNodeContext.setBreakingNode(canBeRootBreakingPoint);
        }

        return result;
      }
    };
  }
  private static boolean staticCanBeARoot(SModel model) {
    return model.getModule() instanceof TransientModelsModule || SModelStereotype.isGeneratorModel(model);
  }
  private static final SNodePointer canBeRootBreakingPoint = new SNodePointer("r:018883b3-a025-4541-bf87-9347bd073b49(com.mbeddr.doc.gen_xhtml.constraints)", "5049963863857445829");

  private static final class CONCEPTS {
    /*package*/ static final SConcept XHTMLFile$D0 = MetaAdapterFactory.getConcept(0x2dec08523a214c4eL, 0xa68cb05236cc37f2L, 0x7a98c0ae07a8e1c8L, "com.mbeddr.doc.gen_xhtml.structure.XHTMLFile");
  }
}
