package com.mbeddr.ext.statemachines.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.ListScope;
import com.mbeddr.ext.statemachines.behavior.AbstractState__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class AbstractTransition_Constraints extends BaseConstraintsDescriptor {
  /*package*/ AbstractTransition_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.AbstractTransition$Oa, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.targetState$DvvA, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:83bfdebe-5142-4e25-be3f-92ce5f6940d7(com.mbeddr.ext.statemachines.constraints)", "4048193437558525721");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          return ListScope.forResolvableElements(AbstractState__BehaviorDescriptor.reachableTargetStates_id3FSHg1aCVVq.invoke(SNodeOperations.getNodeAncestor(_context.getReferenceNode(), CONCEPTS.AbstractState$pd, false, false)));
        }
      };
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AbstractTransition$Oa = MetaAdapterFactory.getConcept(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x11a25169722e07bbL, "com.mbeddr.ext.statemachines.structure.AbstractTransition");
    /*package*/ static final SConcept AbstractState$pd = MetaAdapterFactory.getConcept(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x3af8b5004a9a92a2L, "com.mbeddr.ext.statemachines.structure.AbstractState");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink targetState$DvvA = MetaAdapterFactory.getReferenceLink(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x11a25169722e07bbL, 0x11a25169722f85feL, "targetState");
  }
}
