package com.mbeddr.ext.statemachines.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.typechecking.TypecheckingFacade;
import com.mbeddr.ext.statemachines.behavior.Statemachine__BehaviorDescriptor;
import com.mbeddr.ext.statemachines.behavior.SmVarTarget__BehaviorDescriptor;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.internal.collections.runtime.Sequence;
import com.mbeddr.ext.statemachines.behavior.StatemachineVariableDeclaration__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class SmVarTarget_Constraints extends BaseConstraintsDescriptor {
  /*package*/ SmVarTarget_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.SmVarTarget$b0, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.variable$tDkR, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:83bfdebe-5142-4e25-be3f-92ce5f6940d7(com.mbeddr.ext.statemachines.constraints)", "4048193437558481649");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          SNode machine = SLinkOperations.getTarget(SNodeOperations.cast(TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(SNodeOperations.cast((((_context.getReferenceNode() == null) ? _context.getContextNode() : SNodeOperations.getParent(_context.getReferenceNode()))), CONCEPTS.GenericDotExpression$uQ), LINKS.expression$PfNq)), CONCEPTS.StatemachineType$wP), LINKS.machine$eifp);
          Iterable<SNode> allVars = Statemachine__BehaviorDescriptor.localVariables_id6MWlM4926s9.invoke(machine);
          if ((boolean) SmVarTarget__BehaviorDescriptor.isInTest_id4ZnMRYVio3$.invoke(_context.getReferenceNode())) {
            return ListScope.forResolvableElements(allVars);
          } else {
            return ListScope.forResolvableElements(Sequence.fromIterable(allVars).where((it) -> (boolean) StatemachineVariableDeclaration__BehaviorDescriptor.visibleExternally_id13QNHYGEUZl.invoke(it)));
          }
        }
      };
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept SmVarTarget$b0 = MetaAdapterFactory.getConcept(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x54e848376f19f2d5L, "com.mbeddr.ext.statemachines.structure.SmVarTarget");
    /*package*/ static final SConcept GenericDotExpression$uQ = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x401df715da462c0cL, "com.mbeddr.core.expressions.structure.GenericDotExpression");
    /*package*/ static final SConcept StatemachineType$wP = MetaAdapterFactory.getConcept(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x6cf6e22eb96bd531L, "com.mbeddr.ext.statemachines.structure.StatemachineType");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink variable$tDkR = MetaAdapterFactory.getReferenceLink(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x54e848376f19f2d5L, 0x54e848376f19f39aL, "variable");
    /*package*/ static final SContainmentLink expression$PfNq = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x29b5b7c4a3763232L, 0x64ae61a4018a9c50L, "expression");
    /*package*/ static final SReferenceLink machine$eifp = MetaAdapterFactory.getReferenceLink(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x6cf6e22eb96bd531L, 0x6cf6e22eb96bd532L, "machine");
  }
}
