package com.mbeddr.ext.statemachines.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.ListScope;
import com.mbeddr.ext.statemachines.behavior.Statemachine__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.typechecking.TypecheckingFacade;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class StatemachineTestStep_Constraints extends BaseConstraintsDescriptor {
  /*package*/ StatemachineTestStep_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.StatemachineTestStep$X2, initContext);
    record(new RD1(this));
    record(new RD2(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.resultingState$Qw$U, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:83bfdebe-5142-4e25-be3f-92ce5f6940d7(com.mbeddr.ext.statemachines.constraints)", "4048193437558476778");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          return ListScope.forResolvableElements(Statemachine__BehaviorDescriptor.allNonCompositeStates_id4h2fJwlRafD.invoke(SLinkOperations.getTarget(SNodeOperations.cast(TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(SNodeOperations.cast((((_context.getReferenceNode() == null) ? _context.getContextNode() : SNodeOperations.getParent(_context.getReferenceNode()))), CONCEPTS.StatemachineTestStatement$V_), LINKS.statemachine$QvQq)), CONCEPTS.StatemachineType$wP), LINKS.machine$eifp)));
        }
      };
    }
  }
  /*package*/ static final class RD2 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD2(ConstraintsDescriptor container) {
      super(LINKS.event$QwlT, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:83bfdebe-5142-4e25-be3f-92ce5f6940d7(com.mbeddr.ext.statemachines.constraints)", "4048193437558474297");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          return ListScope.forResolvableElements(Statemachine__BehaviorDescriptor.inEvents_id6MWlM4926ut.invoke(SLinkOperations.getTarget(SNodeOperations.cast(TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(SNodeOperations.cast((((_context.getReferenceNode() == null) ? _context.getContextNode() : SNodeOperations.getParent(_context.getReferenceNode()))), CONCEPTS.StatemachineTestStatement$V_), LINKS.statemachine$QvQq)), CONCEPTS.StatemachineType$wP), LINKS.machine$eifp)));
        }
      };
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept StatemachineTestStep$X2 = MetaAdapterFactory.getConcept(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x4070c9f3cc3fba9cL, "com.mbeddr.ext.statemachines.structure.StatemachineTestStep");
    /*package*/ static final SConcept StatemachineTestStatement$V_ = MetaAdapterFactory.getConcept(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x4070c9f3cc3fba99L, "com.mbeddr.ext.statemachines.structure.StatemachineTestStatement");
    /*package*/ static final SConcept StatemachineType$wP = MetaAdapterFactory.getConcept(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x6cf6e22eb96bd531L, "com.mbeddr.ext.statemachines.structure.StatemachineType");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink resultingState$Qw$U = MetaAdapterFactory.getReferenceLink(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x4070c9f3cc3fba9cL, 0x4070c9f3cc3fba9eL, "resultingState");
    /*package*/ static final SContainmentLink statemachine$QvQq = MetaAdapterFactory.getContainmentLink(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x4070c9f3cc3fba99L, 0x4070c9f3cc3fba9bL, "statemachine");
    /*package*/ static final SReferenceLink machine$eifp = MetaAdapterFactory.getReferenceLink(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x6cf6e22eb96bd531L, 0x6cf6e22eb96bd532L, "machine");
    /*package*/ static final SReferenceLink event$QwlT = MetaAdapterFactory.getReferenceLink(0x564e97d68fb741f5L, 0xbfc1c7ed376efd62L, 0x4070c9f3cc3fba9cL, 0x4070c9f3cc3fba9dL, "event");
  }
}
