package com.mbeddr.mpsutil.bldoc.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class RootRefWord_Constraints extends BaseConstraintsDescriptor {
  /*package*/ RootRefWord_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.RootRefWord$6C, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.root$zl0b, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:13eee7f4-9035-433e-9c40-eb6f59fa18be(com.mbeddr.mpsutil.bldoc.constraints)", "5358654548920963293");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          return ListScope.forResolvableElements(SModelOperations.rootsIncludingImported(SNodeOperations.getModel(_context.getContextNode()), CONCEPTS.INamedConcept$Kd));
        }
      };
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept RootRefWord$6C = MetaAdapterFactory.getConcept(0xf3b3dc28fee349e1L, 0xa46e685e96389094L, 0x4a5dc3ebbe76ecd7L, "com.mbeddr.mpsutil.bldoc.structure.RootRefWord");
    /*package*/ static final SInterfaceConcept INamedConcept$Kd = MetaAdapterFactory.getInterfaceConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, "jetbrains.mps.lang.core.structure.INamedConcept");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink root$zl0b = MetaAdapterFactory.getReferenceLink(0xf3b3dc28fee349e1L, 0xa46e685e96389094L, 0x4a5dc3ebbe76ecd7L, 0x4a5dc3ebbe76ecd8L, "root");
  }
}
