package com.mbeddr.mpsutil.contextactions.runtime;

/*Generated by MPS */

import jetbrains.mps.openapi.intentions.IntentionExecutable;
import org.jetbrains.mps.openapi.model.SNode;
import javax.swing.Icon;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import java.util.Collections;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.EditorComponent;

public class IntentionAction extends AbstractContextAction implements IContextAction {

  private String myFolder;
  private IntentionExecutable myIntention;
  private SNode mySNode;
  private IContext myContext;
  private Icon myIcon;
  private String myLabel;

  public IntentionAction(IntentionExecutable intention, SNode snode, String folder, IContext context, Icon icon, String label) {
    myIntention = intention;
    mySNode = snode;
    myFolder = folder;
    myContext = context;
    myIcon = icon;
    myLabel = label;
  }

  @Override
  public void execute(IContext context) {
    myIntention.execute(mySNode, check_hmp029_b0a0a01(context.getEditorComponent()));
  }

  @Override
  @NotNull
  public List<String> getFolders(IContext context) {
    return Collections.singletonList(myFolder);
  }

  @Override
  public Icon getIcon(IContext context) {
    return myIcon;
  }

  @Override
  @NotNull
  public String getLabel(IContext context) {
    return myLabel;
  }

  @Nullable
  @Override
  public String getTooltip(IContext context) {
    return myIntention.getDescription(mySNode, check_hmp029_b0a0a81(context.getEditorComponent()));
  }

  @NotNull
  public ContextActionId getId() {
    return new ContextActionId(myIntention.getDescriptor().getPersistentStateKey() + "#" + getLabel(myContext));
  }
  private static EditorContext check_hmp029_b0a0a01(EditorComponent checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getEditorContext();
    }
    return null;
  }
  private static EditorContext check_hmp029_b0a0a81(EditorComponent checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getEditorContext();
    }
    return null;
  }
}
