package com.mbeddr.ext.units.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.builder.SNodeBuilder;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SConcept;

public class typeof_AnnotatedExpression_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_AnnotatedExpression_InferenceRule() {
  }
  public void applyRule(final SNode expression, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      final SNode innerType = typeCheckingContext.typeOf(SLinkOperations.getTarget(expression, LINKS.innerExpression$bkfw), "r:f5260afd-8327-4c3e-bf02-c81ea8a33729(com.mbeddr.ext.units.typesystem)", "4959640877382070192", true);
      typeCheckingContext.whenConcrete(innerType, () -> {
        {
          SNode _nodeToCheck_1029348928467 = expression;
          EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:f5260afd-8327-4c3e-bf02-c81ea8a33729(com.mbeddr.ext.units.typesystem)", "4959640877382005723", 0, null);
          typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:f5260afd-8327-4c3e-bf02-c81ea8a33729(com.mbeddr.ext.units.typesystem)", "4959640877382005478", true), (SNode) createAnnotatedType_x82aj0_a1a0c0a0b0a1a0a1(SNodeOperations.copyNode(SLinkOperations.getTarget(expression, LINKS.specification$6D2X)), SNodeOperations.cast(typeCheckingContext.getExpandedNode(innerType), CONCEPTS.IType$a9)), _info_12389875345);
        }
      }, "r:f5260afd-8327-4c3e-bf02-c81ea8a33729(com.mbeddr.ext.units.typesystem)", "4959640877382069981", false, false);
    }

  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.AnnotatedExpression$Ec;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }
  private static SNode createAnnotatedType_x82aj0_a1a0c0a0b0a1a0a1(SNode p0, SNode p1) {
    SNodeBuilder n0 = new SNodeBuilder().init(CONCEPTS.AnnotatedType$I9);
    n0.forChild(LINKS.specification$Q3Ej).initNode(p0, CONCEPTS.UnitSpecification$om, true);
    n0.forChild(LINKS.valueType$2o7e).initNode(p1, CONCEPTS.IType$a9, true);
    return n0.getResult();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink innerExpression$bkfw = MetaAdapterFactory.getContainmentLink(0xd04a6cc773e4069L, 0xb9b011884b2ff1c8L, 0x73b48a125b0c5df0L, 0x73b48a125b0d373aL, "innerExpression");
    /*package*/ static final SContainmentLink specification$6D2X = MetaAdapterFactory.getContainmentLink(0xd04a6cc773e4069L, 0xb9b011884b2ff1c8L, 0x73b48a125b0c5df0L, 0x73b48a125b0e856dL, "specification");
    /*package*/ static final SContainmentLink specification$Q3Ej = MetaAdapterFactory.getContainmentLink(0xd04a6cc773e4069L, 0xb9b011884b2ff1c8L, 0x73b48a125b0f3f14L, 0x73b48a125b0f3f48L, "specification");
    /*package*/ static final SContainmentLink valueType$2o7e = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0xa526fcd7806eb53L, 0x65d0a4755f54174cL, "valueType");
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IType$a9 = MetaAdapterFactory.getInterfaceConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x11f8a0774f2L, "jetbrains.mps.lang.core.structure.IType");
    /*package*/ static final SConcept AnnotatedExpression$Ec = MetaAdapterFactory.getConcept(0xd04a6cc773e4069L, 0xb9b011884b2ff1c8L, 0x73b48a125b0c5df0L, "com.mbeddr.ext.units.structure.AnnotatedExpression");
    /*package*/ static final SConcept AnnotatedType$I9 = MetaAdapterFactory.getConcept(0xd04a6cc773e4069L, 0xb9b011884b2ff1c8L, 0x73b48a125b0f3f14L, "com.mbeddr.ext.units.structure.AnnotatedType");
    /*package*/ static final SConcept UnitSpecification$om = MetaAdapterFactory.getConcept(0xd04a6cc773e4069L, 0xb9b011884b2ff1c8L, 0x73b48a125b0d411dL, "com.mbeddr.ext.units.structure.UnitSpecification");
  }
}
