package com.mbeddr.cc.var.annotations.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public final class FeatureCondition__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x17fba0eaf154a23L, 0xb0a802b5c1141e75L, 0x24465732fc60006dL, "com.mbeddr.cc.var.annotations.structure.FeatureCondition");

  public static final SMethod<Long> getCharacteristicNumber_id2h6lNbWo02l = new SMethodBuilder<Long>(new SJavaCompoundTypeImpl(Long.TYPE)).name("getCharacteristicNumber").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(2613872510229282965L).languageId(0xb0a802b5c1141e75L, 0x17fba0eaf154a23L).build2();
  public static final SMethod<Boolean> isSelectedInRenderingConfiguration_id2h6lNbWo02u = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("isSelectedInRenderingConfiguration").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(2613872510229282974L).languageId(0xb0a802b5c1141e75L, 0x17fba0eaf154a23L).build2();
  public static final SMethod<Boolean> isSelectedInConfiguration_id7cHde$FkSjp = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("isSelectedInConfiguration").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(8299347864372610265L).languageId(0xb0a802b5c1141e75L, 0x17fba0eaf154a23L).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));
  public static final SMethod<Boolean> isSelectedInTransformationConfiguration_id5JmNU9PAaKn = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("isSelectedInTransformationConfiguration").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(6617704999132113943L).languageId(0xb0a802b5c1141e75L, 0x17fba0eaf154a23L).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));
  public static final SMethod<SNode> renderingConfiguration_id6tR2451fqEz = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("renderingConfiguration").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7455436784495602339L).languageId(0xb0a802b5c1141e75L, 0x17fba0eaf154a23L).build2();
  public static final SMethod<Boolean> e_id2h6lNbWo02B = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("e").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(2613872510229282983L).languageId(0xb0a802b5c1141e75L, 0x17fba0eaf154a23L).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""), SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));
  public static final SMethod<Long> n_id2h6lNbWo046 = new SMethodBuilder<Long>(new SJavaCompoundTypeImpl(Long.TYPE)).name("n").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(2613872510229283078L).languageId(0xb0a802b5c1141e75L, 0x17fba0eaf154a23L).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getCharacteristicNumber_id2h6lNbWo02l, isSelectedInRenderingConfiguration_id2h6lNbWo02u, isSelectedInConfiguration_id7cHde$FkSjp, isSelectedInTransformationConfiguration_id5JmNU9PAaKn, renderingConfiguration_id6tR2451fqEz, e_id2h6lNbWo02B, n_id2h6lNbWo046);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static long getCharacteristicNumber_id2h6lNbWo02l(@NotNull SNode __thisNode__) {
    return ((long) FeatureCondition__BehaviorDescriptor.n_id2h6lNbWo046.invoke(__thisNode__, SLinkOperations.getTarget(__thisNode__, LINKS.expr$Myds)));
  }
  /*package*/ static boolean isSelectedInRenderingConfiguration_id2h6lNbWo02u(@NotNull SNode __thisNode__) {
    return ((boolean) FeatureCondition__BehaviorDescriptor.isSelectedInConfiguration_id7cHde$FkSjp.invoke(__thisNode__, FeatureCondition__BehaviorDescriptor.renderingConfiguration_id6tR2451fqEz.invoke(__thisNode__)));
  }
  /*package*/ static boolean isSelectedInConfiguration_id7cHde$FkSjp(@NotNull SNode __thisNode__, SNode c) {
    boolean selectedDirectly = ((boolean) FeatureCondition__BehaviorDescriptor.e_id2h6lNbWo02B.invoke(__thisNode__, SLinkOperations.getTarget(__thisNode__, LINKS.expr$Myds), c));
    if (selectedDirectly) {
      return true;
    }
    for (SNode mapping : ListSequence.fromList(SLinkOperations.getChildren(c, LINKS.additionalMappings$EpA4))) {
      if (((boolean) FeatureCondition__BehaviorDescriptor.e_id2h6lNbWo02B.invoke(__thisNode__, SLinkOperations.getTarget(__thisNode__, LINKS.expr$Myds), mapping))) {
        return true;
      }
    }
    return false;
  }
  /*package*/ static boolean isSelectedInTransformationConfiguration_id5JmNU9PAaKn(@NotNull SNode __thisNode__, SNode config) {
    return ((boolean) FeatureCondition__BehaviorDescriptor.e_id2h6lNbWo02B.invoke(__thisNode__, SLinkOperations.getTarget(__thisNode__, LINKS.expr$Myds), config));
  }
  /*package*/ static SNode renderingConfiguration_id6tR2451fqEz(@NotNull SNode __thisNode__) {
    return new IAttributeDescriptor.NodeAttribute(CONCEPTS.FeatureModelConfiguration$dw).get(ListSequence.fromList(SNodeOperations.getNodeAncestors(__thisNode__, null, false)).last());
  }
  /*package*/ static boolean e_id2h6lNbWo02B(@NotNull SNode __thisNode__, SNode node, SNode mapping) {
    FeatureConditionEvalHelper h = new FeatureConditionEvalHelper(mapping);
    return h.isSelected(SNodeOperations.cast(node, CONCEPTS.Expression$bT));
  }
  /*package*/ static long n_id2h6lNbWo046(@NotNull SNode __thisNode__, SNode node) {
    if (SNodeOperations.isInstanceOf(node, CONCEPTS.FeatureRef$MU) && SLinkOperations.getTarget(SNodeOperations.cast(node, CONCEPTS.FeatureRef$MU), LINKS.feature$4n8N) != null && SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(node, CONCEPTS.FeatureRef$MU), LINKS.feature$4n8N), PROPS.name$MnvL) != null) {
      return SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(node, CONCEPTS.FeatureRef$MU), LINKS.feature$4n8N), PROPS.name$MnvL).hashCode();
    } else if (SNodeOperations.isInstanceOf(node, CONCEPTS.AndExpression$P)) {
      return ((long) FeatureCondition__BehaviorDescriptor.n_id2h6lNbWo046.invoke(__thisNode__, SLinkOperations.getTarget(SNodeOperations.cast(node, CONCEPTS.AndExpression$P), LINKS.left$SkXz))) + ((long) FeatureCondition__BehaviorDescriptor.n_id2h6lNbWo046.invoke(__thisNode__, SLinkOperations.getTarget(SNodeOperations.cast(node, CONCEPTS.AndExpression$P), LINKS.right$Slc$)));
    } else if (SNodeOperations.isInstanceOf(node, CONCEPTS.OrExpression$1N)) {
      return ((long) FeatureCondition__BehaviorDescriptor.n_id2h6lNbWo046.invoke(__thisNode__, SLinkOperations.getTarget(SNodeOperations.cast(node, CONCEPTS.OrExpression$1N), LINKS.left$SkXz))) * ((long) FeatureCondition__BehaviorDescriptor.n_id2h6lNbWo046.invoke(__thisNode__, SLinkOperations.getTarget(SNodeOperations.cast(node, CONCEPTS.OrExpression$1N), LINKS.right$Slc$)));
    } else if (SNodeOperations.isInstanceOf(node, CONCEPTS.NotExpression$pF)) {
      return 7 * ((long) FeatureCondition__BehaviorDescriptor.n_id2h6lNbWo046.invoke(__thisNode__, SLinkOperations.getTarget(SNodeOperations.cast(node, CONCEPTS.NotExpression$pF), LINKS.expression$PfNq)));
    } else {
      return 100000;
    }
  }

  /*package*/ FeatureCondition__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((Long) getCharacteristicNumber_id2h6lNbWo02l(node));
      case 1:
        return (T) ((Boolean) isSelectedInRenderingConfiguration_id2h6lNbWo02u(node));
      case 2:
        return (T) ((Boolean) isSelectedInConfiguration_id7cHde$FkSjp(node, (SNode) parameters[0]));
      case 3:
        return (T) ((Boolean) isSelectedInTransformationConfiguration_id5JmNU9PAaKn(node, (SNode) parameters[0]));
      case 4:
        return (T) ((SNode) renderingConfiguration_id6tR2451fqEz(node));
      case 5:
        return (T) ((Boolean) e_id2h6lNbWo02B(node, (SNode) parameters[0], (SNode) parameters[1]));
      case 6:
        return (T) ((Long) n_id2h6lNbWo046(node, (SNode) parameters[0]));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink expr$Myds = MetaAdapterFactory.getContainmentLink(0x17fba0eaf154a23L, 0xb0a802b5c1141e75L, 0x24465732fc60006dL, 0x24465732fc60006eL, "expr");
    /*package*/ static final SContainmentLink additionalMappings$EpA4 = MetaAdapterFactory.getContainmentLink(0x17fba0eaf154a23L, 0xb0a802b5c1141e75L, 0x92cd87784518100L, 0x4046b90ba729ffL, "additionalMappings");
    /*package*/ static final SReferenceLink feature$4n8N = MetaAdapterFactory.getReferenceLink(0xe401b44780194ccdL, 0xa72cbfb0230f5782L, 0x6a0e1211f0e3a631L, 0x6a0e1211f0e3a632L, "feature");
    /*package*/ static final SContainmentLink left$SkXz = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x7af69e2e83a1ba34L, 0x7af69e2e83a1ba40L, "left");
    /*package*/ static final SContainmentLink right$Slc$ = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x7af69e2e83a1ba34L, 0x7af69e2e83a1ba41L, "right");
    /*package*/ static final SContainmentLink expression$PfNq = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x29b5b7c4a3763232L, 0x64ae61a4018a9c50L, "expression");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FeatureModelConfiguration$dw = MetaAdapterFactory.getConcept(0x17fba0eaf154a23L, 0xb0a802b5c1141e75L, 0x92cd87784518100L, "com.mbeddr.cc.var.annotations.structure.FeatureModelConfiguration");
    /*package*/ static final SConcept Expression$bT = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x7af69e2e83a1ba32L, "com.mbeddr.core.expressions.structure.Expression");
    /*package*/ static final SConcept FeatureRef$MU = MetaAdapterFactory.getConcept(0xe401b44780194ccdL, 0xa72cbfb0230f5782L, 0x6a0e1211f0e3a631L, "com.mbeddr.cc.var.fm.structure.FeatureRef");
    /*package*/ static final SConcept AndExpression$P = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x7490dc0ede26e048L, "com.mbeddr.core.expressions.structure.AndExpression");
    /*package*/ static final SConcept OrExpression$1N = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x7490dc0ede26e04aL, "com.mbeddr.core.expressions.structure.OrExpression");
    /*package*/ static final SConcept NotExpression$pF = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x352a4cc97cbac907L, "com.mbeddr.core.expressions.structure.NotExpression");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
