package com.mbeddr.mpsutil.contextactions.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class RefactoringReference_SubstituteMenu extends SubstituteMenuBase {
  public RefactoringReference_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for RefactoringReference. Generated from implicit smart reference attribute.", new SNodePointer("r:79fc204c-e983-452d-a03e-6b06e96e9690(com.mbeddr.mpsutil.contextactions.structure)", "5844665283566935815")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_alebd2_a(), CONCEPTS.RefactoringReference$eF));
    result.add(new SMP_Subconcepts_alebd2_b());
    return result;
  }

  public class SMP_ReferenceScope_alebd2_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_alebd2_a() {
      super(CONCEPTS.RefactoringReference$eF, LINKS.refactoring$Er63, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_alebd2_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_alebd2_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "RefactoringReference", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.RefactoringReference$eF);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept RefactoringReference$eF = MetaAdapterFactory.getConcept(0x677f00fb4488405eL, 0x9885abb75d472fd1L, 0x511c6c1bea109f07L, "com.mbeddr.mpsutil.contextactions.structure.RefactoringReference");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink refactoring$Er63 = MetaAdapterFactory.getReferenceLink(0x677f00fb4488405eL, 0x9885abb75d472fd1L, 0x511c6c1bea109f07L, 0x511c6c1bea109f32L, "refactoring");
  }
}
