package com.mbeddr.core.pointers.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.typesystem.inference.EquationInfo;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public class typeof_PointerType_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_PointerType_InferenceRule() {
  }
  public void applyRule(final SNode pt, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      final SNode ttt = typeCheckingContext.typeOf(SLinkOperations.getTarget(pt, LINKS.baseType$zMGV), "r:54210dde-4071-421e-b973-a22bb864eeac(com.mbeddr.core.pointers.typesystem)", "7041589747176524023", true);
      typeCheckingContext.whenConcrete(ttt, () -> {
        SNode t = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x3bf5377ae9044dedL, 0x97545a516023bfaaL, 0x3e0cae5e366d630L, "com.mbeddr.core.pointers.structure.PointerType"));
        SLinkOperations.setTarget(t, LINKS.baseType$zMGV, SNodeOperations.cast(SNodeOperations.copyNode(typeCheckingContext.getExpandedNode(ttt)), CONCEPTS.IType$a9));
        SPropertyOperations.assign(t, PROPS.const$VWr7, SPropertyOperations.getBoolean(pt, PROPS.const$VWr7));
        SPropertyOperations.assign(t, PROPS.volatile$hJNe, SPropertyOperations.getBoolean(pt, PROPS.volatile$hJNe));
        {
          SNode _nodeToCheck_1029348928467 = pt;
          EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:54210dde-4071-421e-b973-a22bb864eeac(com.mbeddr.core.pointers.typesystem)", "7041589747176524082", 0, null);
          typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:54210dde-4071-421e-b973-a22bb864eeac(com.mbeddr.core.pointers.typesystem)", "7041589747176524079", true), (SNode) t, _info_12389875345);
        }
      }, "r:54210dde-4071-421e-b973-a22bb864eeac(com.mbeddr.core.pointers.typesystem)", "7041589747176524020", false, false);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.PointerType$HX;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return true;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink baseType$zMGV = MetaAdapterFactory.getContainmentLink(0xa9d696470840491eL, 0xbf392eb0805d2011L, 0x6bbcdccef5e46755L, 0x6bbcdccef5e46756L, "baseType");
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IType$a9 = MetaAdapterFactory.getInterfaceConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x11f8a0774f2L, "jetbrains.mps.lang.core.structure.IType");
    /*package*/ static final SConcept PointerType$HX = MetaAdapterFactory.getConcept(0x3bf5377ae9044dedL, 0x97545a516023bfaaL, 0x3e0cae5e366d630L, "com.mbeddr.core.pointers.structure.PointerType");
  }

  private static final class PROPS {
    /*package*/ static final SProperty const$VWr7 = MetaAdapterFactory.getProperty(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x7af69e2e83a1ba36L, 0x28d183d9a4cc7da8L, "const");
    /*package*/ static final SProperty volatile$hJNe = MetaAdapterFactory.getProperty(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x7af69e2e83a1ba36L, 0x28d183d9a4fae02fL, "volatile");
  }
}
