#!/bin/sh
#set +v

PROC_RET=0


# echo -------------------------------------
# echo comptest
# cd tests/test.ex.ext.components/source_gen/test/ex/ext/components/comptest
# make test
# PROC_RET=$(($?+$PROC_RET))



if [ "$PROC_RET" -ne "0" ]; 
 then
    echo ""
    echo "" 
    echo "================================================"
    echo "================================================" 
    echo "               $PROC_RET test(s) failed"
    echo "================================================"
    echo "================================================"
    echo ""
    echo ""
 else
  echo ""
    echo "" 
    echo "================================================"
    echo "              OK - All tests green"
    echo "================================================"
    echo ""
    echo ""
fi

exit $PROC_RET