package com.mbeddr.core.statements.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.scope.EmptyScope;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.Sequence;
import com.mbeddr.core.statements.behavior.ILocalVarScopeProvider__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;
import com.mbeddr.core.base.behavior.VisibilityControllingAttribute__BehaviorDescriptor;
import jetbrains.mps.lang.scopes.runtime.NamedElementsScope;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class LocalVarRef_Constraints extends BaseConstraintsDescriptor {
  /*package*/ LocalVarRef_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.LocalVarRef$VQ, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.var$YUyC, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:ca045cc4-bf15-4298-974d-854171fafdc0(com.mbeddr.core.statements.constraints)", "2093108837558189301");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          SNode scopeProvider = SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.ILocalVarScopeProvider$Dq, true, false);

          if (scopeProvider == null) {
            return new EmptyScope();
          } else {
            List<SNode> declarations = ListSequence.fromList(new ArrayList<SNode>());
            for (SNode declaration : Sequence.fromIterable(ILocalVarScopeProvider__BehaviorDescriptor.getLocalVarScope_id2tBHhziI8iF.invoke(scopeProvider, (((_context.getReferenceNode() == null) ? _context.getContextNode() : SNodeOperations.getParent(_context.getReferenceNode()))), ((int) _context.getPosition())).getVisibleLocalVars())) {
              if (!(new IAttributeDescriptor.NodeAttribute(CONCEPTS.VisibilityControllingAttribute$UF).get(declaration) != null && !((boolean) VisibilityControllingAttribute__BehaviorDescriptor.isCurrentlyVisible_id5aNdPeN2Pp4.invoke(new IAttributeDescriptor.NodeAttribute(CONCEPTS.VisibilityControllingAttribute$UF).get(declaration))))) {
                ListSequence.fromList(declarations).addElement(declaration);
              }
            }
            return new NamedElementsScope(declarations);
          }

        }
      };
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept LocalVarRef$VQ = MetaAdapterFactory.getConcept(0xa9d696470840491eL, 0xbf392eb0805d2011L, 0x1d0c3765e2e1d67aL, "com.mbeddr.core.statements.structure.LocalVarRef");
    /*package*/ static final SInterfaceConcept ILocalVarScopeProvider$Dq = MetaAdapterFactory.getInterfaceConcept(0xa9d696470840491eL, 0xbf392eb0805d2011L, 0x1d0c3765e2e2fcf8L, "com.mbeddr.core.statements.structure.ILocalVarScopeProvider");
    /*package*/ static final SConcept VisibilityControllingAttribute$UF = MetaAdapterFactory.getConcept(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x52b33753b30b563eL, "com.mbeddr.core.base.structure.VisibilityControllingAttribute");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink var$YUyC = MetaAdapterFactory.getReferenceLink(0xa9d696470840491eL, 0xbf392eb0805d2011L, 0x1d0c3765e2e1d67aL, 0x1d0c3765e2e1fe27L, "var");
  }
}
