package com.mbeddr.mpsutil.interpreter.rt;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.HashMap;

public class ContextImpl implements ITypeCachingContext {
  private IEnvironment environment;
  private IMapTypeProvider mapTypeProvider;
  private IInterpreter rootInterpreter;
  private INodeValueCache nodeValueCache;
  private static INodeTypeCache nodeTypeCache;

  public ContextImpl() {
    this(new EnvironmentImpl());
  }

  public ContextImpl(IInterpreter actualInterpreter) {
    this();
    setRootInterpreter(actualInterpreter);
  }

  protected ContextImpl(IEnvironment environment) {
    this.environment = environment;
  }


  @Override
  public IEnvironment getEnvironment() {
    return environment;
  }

  public void pushEnvironment(SNode node, Map<SNode, Object> initialEnvironment) {
    if (initialEnvironment == null) {
      initialEnvironment = MapSequence.fromMap(new HashMap<SNode, Object>());
    }
    this.environment = this.environment.push(node, initialEnvironment);
  }

  public void popEnvironment(SNode node) {
    this.environment = this.environment.pop(node);
  }


  public IMapTypeProvider getMapTypeProvider() {
    return this.mapTypeProvider;
  }
  public void setMapTypeProvider(IMapTypeProvider mapTypeProvider) {
    this.mapTypeProvider = mapTypeProvider;
  }


  public IInterpreter getRootInterpreter() {
    if (rootInterpreter == null) {
      throw new IllegalStateException("rootInterpreter not set");
    }
    return rootInterpreter;
  }
  public void setRootInterpreter(IInterpreter interpreter) {
    this.rootInterpreter = interpreter;
  }


  public INodeValueCache getNodeValueCache() {
    return nodeValueCache;
  }
  public void setNodeValueCache(INodeValueCache cache) {
    this.nodeValueCache = cache;
    this.environment.setCache(cache);

  }

  public INodeTypeCache getNodeTypeCache() {
    if (nodeTypeCache == null) {
      nodeTypeCache = new NodeTypeCacheImpl();
    }
    return nodeTypeCache;
  }

  public void setNodeTypeCache(INodeTypeCache cache) {
    nodeTypeCache = cache;
  }

  @Override
  public LanguageConfig getConfiguration() {
    return new LanguageConfig(true);
  }


}
