package com.mbeddr.core.unittest.migration;

/*Generated by MPS */

import jetbrains.mps.lang.migration.runtime.base.MigrationScriptBase;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import com.mbeddr.core.buildconfig.behavior.Binary__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import com.mbeddr.core.base.behavior.IRequiresConfigItem__BehaviorDescriptor;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import jetbrains.mps.lang.migration.runtime.base.MigrationScriptReference;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SConcept;

public class addConfigItemToBuildConfig extends MigrationScriptBase {
  private final String description = "addConfigItemToBuildConfig";
  public String getCaption() {
    return description;
  }
  @Override
  public boolean isRerunnable() {
    return false;
  }
  public SNode execute(final SModule m) {
    doExecute(m);
    return null;
  }
  public void doExecute(final SModule m) {
    Iterable<SModel> models = m.getModels();
    for (SModel model : Sequence.fromIterable(models)) {
      for (SNode bc : ListSequence.fromList(SModelOperations.roots(model, CONCEPTS.BuildConfiguration$kH))) {


        if (Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(bc, LINKS.configurationItems$HPvE), CONCEPTS.UnitTestConfigItem$uM)).isEmpty()) {
          boolean requiresTestCaseConfigItem = ListSequence.fromList(SLinkOperations.getChildren(bc, LINKS.binaries$R6lf)).any((binary) -> {

            return Sequence.fromIterable(Binary__BehaviorDescriptor.allReferencedModules_id3BbcpZJ16uV.invoke(binary)).any((module) -> {

              return ListSequence.fromList(SNodeOperations.getNodeDescendants(module, CONCEPTS.IRequiresConfigItem$Ys, false, new SAbstractConcept[]{})).any((reqConfigItem) -> {
                return ListSequence.fromList(IRequiresConfigItem__BehaviorDescriptor.getConfigItem_id5HxjapwgqMb.invoke(SNodeOperations.asSConcept(SNodeOperations.getConcept(reqConfigItem)))).any((configItem) -> configItem == SNodeOperations.getNode("r:734c02dd-cc16-4184-99eb-5fd9f43aa37e(com.mbeddr.core.unittest.structure)", "8610007178384196427"));

              });
            });
          });
          if (requiresTestCaseConfigItem) {
            SNodeFactoryOperations.addNewChild(bc, LINKS.configurationItems$HPvE, CONCEPTS.UnitTestConfigItem$uM);
          }
        }

      }
    }
  }
  public MigrationScriptReference getReference() {
    return new MigrationScriptReference(MetaAdapterFactory.getLanguage(0x6d68b77b6994918L, 0x83b8857e63787800L, "com.mbeddr.core.unittest"), 1);
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink binaries$R6lf = MetaAdapterFactory.getContainmentLink(0x2d7fadf533f64e80L, 0xa78f0f739add2bdeL, 0x6b1af9f9f43c2f48L, 0x46097107c8de43cbL, "binaries");
    /*package*/ static final SContainmentLink configurationItems$HPvE = MetaAdapterFactory.getContainmentLink(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x3de41a718bc20029L, 0x3de41a718bc2002aL, "configurationItems");
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IRequiresConfigItem$Ys = MetaAdapterFactory.getInterfaceConcept(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x16fdbcc716a403ecL, "com.mbeddr.core.base.structure.IRequiresConfigItem");
    /*package*/ static final SConcept UnitTestConfigItem$uM = MetaAdapterFactory.getConcept(0x6d68b77b6994918L, 0x83b8857e63787800L, 0x777ce3e93527434bL, "com.mbeddr.core.unittest.structure.UnitTestConfigItem");
    /*package*/ static final SConcept BuildConfiguration$kH = MetaAdapterFactory.getConcept(0x2d7fadf533f64e80L, 0xa78f0f739add2bdeL, 0x6b1af9f9f43c2f48L, "com.mbeddr.core.buildconfig.structure.BuildConfiguration");
  }
}
