package com.mbeddr.cc.requirements.csv.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public final class AddCsvImportAnnotation_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public AddCsvImportAnnotation_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:26fb8128-b456-4a0d-a694-b72b761d8d18(com.mbeddr.cc.requirements.csv.intentions)", "561942466025368891"));
  }

  @Override
  public String getPresentation() {
    return "AddCsvImportAnnotation";
  }

  @Override
  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }

    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "REQ: " + ("Add CSV Import");
    }

    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      new IAttributeDescriptor.NodeAttribute(CONCEPTS.CvsImportAnnotation$qL).setNew(node);
    }

    @Override
    public boolean isApplicable(final SNode node, final EditorContext editorContext) {
      if (!(isApplicableToNode(node, editorContext))) {
        return false;
      }
      return true;
    }

    private boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
      return (new IAttributeDescriptor.NodeAttribute(CONCEPTS.CvsImportAnnotation$qL).get(node) == null);
    }


    @Override
    public IntentionDescriptor getDescriptor() {
      return AddCsvImportAnnotation_Intention.this;
    }

  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept CvsImportAnnotation$qL = MetaAdapterFactory.getConcept(0x698eb129303c4c1cL, 0xb3979e30753d40b2L, 0x7cc6bb20fa62a0bL, "com.mbeddr.cc.requirements.csv.structure.CvsImportAnnotation");
  }
}
