package com.mbeddr.mpsutil.placeholderTextList.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_CellModel_PlaceholderTextList;
  private ConceptPresentation props_QueryFunction_PlaceholderText;
  private ConceptPresentation props_StubCellModel_PlaceholderTextList;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.CellModel_PlaceholderTextList:
        if (props_CellModel_PlaceholderTextList == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("multiple aggregation with placeholder text");
          cpb.presentationByReference(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x10964446123L, 0x10973779681L, "relationDeclaration", "PT%", "%");
          props_CellModel_PlaceholderTextList = cpb.create();
        }
        return props_CellModel_PlaceholderTextList;
      case LanguageConceptSwitch.QueryFunction_PlaceholderText:
        if (props_QueryFunction_PlaceholderText == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("placeholder text");
          props_QueryFunction_PlaceholderText = cpb.create();
        }
        return props_QueryFunction_PlaceholderText;
      case LanguageConceptSwitch.StubCellModel_PlaceholderTextList:
        if (props_StubCellModel_PlaceholderTextList == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("StubCellModel_PlaceholderTextList");
          props_StubCellModel_PlaceholderTextList = cpb.create();
        }
        return props_StubCellModel_PlaceholderTextList;
    }
    return null;
  }
}
