package com.mbeddr.ext.components.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.typechecking.TypecheckingFacade;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import com.mbeddr.ext.components.behavior.PortType__BehaviorDescriptor;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_PortVarOpCallExpr_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_PortVarOpCallExpr_NonTypesystemRule() {
  }
  public void applyRule(final SNode portVarOpCallExpr, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      final SNode portType = TypecheckingFacade.getFromContext().getTypeOf(SLinkOperations.getTarget(portVarOpCallExpr, LINKS.expression$PfNq));
      if (SNodeOperations.isInstanceOf(portType, CONCEPTS.PortType$gc)) {
        if (!(SNodeOperations.isInstanceOf(SLinkOperations.getTarget(portVarOpCallExpr, LINKS.expression$PfNq), CONCEPTS.ArrayAccessExpr$IH) || SNodeOperations.isInstanceOf(SLinkOperations.getTarget(portVarOpCallExpr, LINKS.expression$PfNq), CONCEPTS.PortItExpression$JS)) && (boolean) PortType__BehaviorDescriptor.isMultiple_id1tylWje6zna.invoke(portType) && !(SNodeOperations.isInstanceOf(SLinkOperations.getTarget(SLinkOperations.getTarget(portVarOpCallExpr, LINKS.operation$jSaZ), LINKS.type$sXU3), CONCEPTS.VoidType$GT))) {
          {
            final MessageTarget errorTarget = new NodeMessageTarget();
            IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(portVarOpCallExpr, "multiple operation calls are only supported for operations returning void", "r:c480d4b6-a379-41b5-b76a-c94ccc817c4e(com.mbeddr.ext.components.typesystem)", "1685005713378442811", null, errorTarget);
          }
        }
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.PortVarOpCallExpr$ux;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink expression$PfNq = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x29b5b7c4a3763232L, 0x64ae61a4018a9c50L, "expression");
    /*package*/ static final SReferenceLink operation$jSaZ = MetaAdapterFactory.getReferenceLink(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x707ac195dd618205L, 0x707ac195dd618208L, "operation");
    /*package*/ static final SContainmentLink type$sXU3 = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x46a2a92ac61b183L, 0x46a2a92ac61b184L, "type");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept PortType$gc = MetaAdapterFactory.getConcept(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x176257c4ce13e2faL, "com.mbeddr.ext.components.structure.PortType");
    /*package*/ static final SConcept VoidType$GT = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x6d872ef9245a0d19L, "com.mbeddr.core.expressions.structure.VoidType");
    /*package*/ static final SConcept ArrayAccessExpr$IH = MetaAdapterFactory.getConcept(0x3bf5377ae9044dedL, 0x97545a516023bfaaL, 0x572f431af7922901L, "com.mbeddr.core.pointers.structure.ArrayAccessExpr");
    /*package*/ static final SConcept PortItExpression$JS = MetaAdapterFactory.getConcept(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x5bd0f22423fa0ee2L, "com.mbeddr.ext.components.structure.PortItExpression");
    /*package*/ static final SConcept PortVarOpCallExpr$ux = MetaAdapterFactory.getConcept(0x97d2424451db4e2eL, 0x97fc7bd73b1f5f40L, 0x176257c4ce6b1de1L, "com.mbeddr.ext.components.structure.PortVarOpCallExpr");
  }
}
