<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SampleRoot" nsURI="http://test/amalthea/ecore/model" nsPrefix="test.amaltheaecore.model">
  <eClassifiers xsi:type="ecore:EClass" name="testClass1" eSuperTypes="#//testClass3 #//testClass2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute1Class1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newReference" eType="#//testClass1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="testClass2" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute2Class2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="testClass3" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testreference3" upperBound="-1"
        eType="#//testClass2" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="enumTest2">
    <eLiterals name="val1" literal="val1"/>
    <eLiterals name="val2" value="1" literal="val2"/>
    <eLiterals name="val3" value="2" literal="val3"/>
  </eClassifiers>
</ecore:EPackage>
