package com.mbeddr.mpsutil.dataflow.ui.plugin;

/*Generated by MPS */

import jetbrains.mps.ide.dataFlow.presentation.JumpBlock;
import jetbrains.mps.lang.dataFlow.framework.instructions.Instruction;
import org.jetbrains.mps.openapi.model.SNodeReference;

public class InterProcJumpBlock extends JumpBlock implements IInterProcVisualizationNode {

  protected Instruction instruction;

  public InterProcJumpBlock(Instruction instruction, int x, int y, int width, int height, SNodeReference source, String caption, String ruleNodeReference) {
    super(x, y, width, height, source, caption, ruleNodeReference);
    this.instruction = instruction;
  }

  @Override
  public Instruction getInstruction() {
    return instruction;
  }

}
