package com.mbeddr.cc.requirements.scenarios.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.scope.ListScope;
import com.mbeddr.cc.requirements.scenarios.behavior.Participant__BehaviorDescriptor;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import com.mbeddr.cc.requirements.scenarios.behavior.ICallContext__BehaviorDescriptor;
import jetbrains.mps.scope.EmptyScope;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class DataItemRef_Constraints extends BaseConstraintsDescriptor {
  public DataItemRef_Constraints() {
    super(CONCEPTS.DataItemRef$5j);
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    BaseReferenceConstraintsDescriptor d0 = new BaseReferenceConstraintsDescriptor(LINKS.item$S4AR, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:91abe641-b5f9-4ad6-8439-513d78a20e8f(com.mbeddr.cc.requirements.scenarios.constraints)", "5744000828452990971");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            SNode c = SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.Participant$Q5, true, false);
            if (c != null) {
              return ListScope.forResolvableElements(Participant__BehaviorDescriptor.availableDataItems_id5_PV_QzOjx0.invoke(c));
            }
            SNode call = SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.Call$eV, true, false);
            if (ListSequence.fromList(SLinkOperations.getChildren(call, LINKS.args$QrOQ)).any((it) -> ListSequence.fromList(SNodeOperations.getNodeDescendants(it, null, true, new SAbstractConcept[]{})).contains((((_context.getReferenceNode() == null) ? _context.getContextNode() : SNodeOperations.getParent(_context.getReferenceNode())))))) {
              return ListScope.forResolvableElements(Participant__BehaviorDescriptor.availableDataItems_id5_PV_QzOjx0.invoke(ICallContext__BehaviorDescriptor.getContextParticipant_id4YQM_89uRDd.invoke(SNodeOperations.getNodeAncestor(call, CONCEPTS.ICallContext$Wj, false, false))));
            }
            SNode ctx = SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.ICallContext$Wj, true, false);
            if (ctx != null) {
              return ListScope.forResolvableElements(Participant__BehaviorDescriptor.availableDataItems_id5_PV_QzOjx0.invoke(ICallContext__BehaviorDescriptor.getContextParticipant_id4YQM_89uRDd.invoke(ctx)));
            }
            return new EmptyScope();
          }
        };
      }
    };
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(d0.getReference(), d0);
    return references;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DataItemRef$5j = MetaAdapterFactory.getConcept(0xd6714220402d48cbL, 0xa4a288223c6257f6L, 0x4fb6ca52097d6ff1L, "com.mbeddr.cc.requirements.scenarios.structure.DataItemRef");
    /*package*/ static final SConcept Participant$Q5 = MetaAdapterFactory.getConcept(0xd6714220402d48cbL, 0xa4a288223c6257f6L, 0x4fb6ca5209783a14L, "com.mbeddr.cc.requirements.scenarios.structure.Participant");
    /*package*/ static final SConcept Call$eV = MetaAdapterFactory.getConcept(0xd6714220402d48cbL, 0xa4a288223c6257f6L, 0x4fb6ca52097b2b30L, "com.mbeddr.cc.requirements.scenarios.structure.Call");
    /*package*/ static final SInterfaceConcept ICallContext$Wj = MetaAdapterFactory.getInterfaceConcept(0xd6714220402d48cbL, 0xa4a288223c6257f6L, 0x4fb6ca52097b7a48L, "com.mbeddr.cc.requirements.scenarios.structure.ICallContext");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink item$S4AR = MetaAdapterFactory.getReferenceLink(0xd6714220402d48cbL, 0xa4a288223c6257f6L, 0x4fb6ca52097d6ff1L, 0x4fb6ca52097d6ff2L, "item");
    /*package*/ static final SContainmentLink args$QrOQ = MetaAdapterFactory.getContainmentLink(0xd6714220402d48cbL, 0xa4a288223c6257f6L, 0x4fb6ca52097b2b30L, 0x4fb6ca52097d4932L, "args");
  }
}
