package com.mbeddr.core.expressions.editor;

/*Generated by MPS */

import jetbrains.mps.lang.editor.generator.internal.AbstractCellMenuComponent;
import jetbrains.mps.nodeEditor.cellMenu.SubstituteInfoPartExt;
import jetbrains.mps.lang.editor.generator.internal.AbstractCellMenuPart_Generic_Group;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.openapi.editor.menus.EditorMenuDescriptor;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class toggle_PostIncDec extends AbstractCellMenuComponent {
  public toggle_PostIncDec() {
    super(new SubstituteInfoPartExt[]{new UnaryExpression_generic_cellMenu_2h8quv_a0()});
  }
  public static class UnaryExpression_generic_cellMenu_2h8quv_a0 extends AbstractCellMenuPart_Generic_Group {
    public UnaryExpression_generic_cellMenu_2h8quv_a0() {
    }

    protected List<?> createParameterObjects(SNode node, EditorContext editorContext) {
      List<SNode> expressionConcepts = ListSequence.fromList(new ArrayList<SNode>());
      ListSequence.fromList(expressionConcepts).addElement(CONCEPTS.PostDecrementExpression$F3.getDeclarationNode());
      ListSequence.fromList(expressionConcepts).addElement(CONCEPTS.PostIncrementExpression$2Z.getDeclarationNode());
      return expressionConcepts;

    }
    protected void handleAction(Object parameterObject, SNode node, SModel model, EditorContext editorContext) {
      this.handleAction_impl((SNode) parameterObject, node, model, editorContext);
    }
    private void handleAction_impl(SNode parameterObject, SNode node, SModel model, EditorContext editorContext) {
      SNode newInstance = SNodeFactoryOperations.createNewNode(SNodeFactoryOperations.asInstanceConcept(parameterObject), node);
      SLinkOperations.setTarget(newInstance, LINKS.expression$PfNq, SLinkOperations.getTarget(node, LINKS.expression$PfNq));
      SNodeOperations.replaceWithAnother(node, newInstance);
    }
    protected boolean isReferentPresentation() {
      return false;
    }

    @Override
    protected EditorMenuDescriptor getEditorMenuDescriptor(Object parameterObject) {
      return new EditorMenuDescriptorBase("generic group with parameter: " + ((parameterObject == null ? "null" : parameterObject.toString())), new SNodePointer("r:53e59391-150a-45ff-930e-2b4fdafb0904(com.mbeddr.core.expressions.editor)", "4420643699735354152"));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept PostDecrementExpression$F3 = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x373071ae5c64aef0L, "com.mbeddr.core.expressions.structure.PostDecrementExpression");
    /*package*/ static final SConcept PostIncrementExpression$2Z = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x3cba500cc5723aaeL, "com.mbeddr.core.expressions.structure.PostIncrementExpression");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink expression$PfNq = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x29b5b7c4a3763232L, 0x64ae61a4018a9c50L, "expression");
  }
}
