package com.mbeddr.core.debug.test.runtime.m1;

/*Generated by MPS */


public class TRExecutingDebugCommandFailedException extends TestRuntimeException {
  public TRExecutingDebugCommandFailedException(String reason) {
    super(reason);
  }
}
