package com.mbeddr.ext.components.embedded.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_InterruptComponentTriggerConfigItem;
  private ConceptPresentation props_InterruptExitHandler;
  private ConceptPresentation props_InterruptProcessed;
  private ConceptPresentation props_InterruptRunnableMapping;
  private ConceptPresentation props_InterruptRunnableMappingActive;
  private ConceptPresentation props_InterruptRunnableReturnValue;
  private ConceptPresentation props_InterruptTrigger;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.InterruptComponentTriggerConfigItem:
        if (props_InterruptComponentTriggerConfigItem == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("allow runnables to be triggered by an interrupt");
          cpb.rawPresentation("interrupt-triggered components");
          props_InterruptComponentTriggerConfigItem = cpb.create();
        }
        return props_InterruptComponentTriggerConfigItem;
      case LanguageConceptSwitch.InterruptExitHandler:
        if (props_InterruptExitHandler == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("InterruptExitHandler");
          props_InterruptExitHandler = cpb.create();
        }
        return props_InterruptExitHandler;
      case LanguageConceptSwitch.InterruptProcessed:
        if (props_InterruptProcessed == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("InterruptProcessed");
          props_InterruptProcessed = cpb.create();
        }
        return props_InterruptProcessed;
      case LanguageConceptSwitch.InterruptRunnableMapping:
        if (props_InterruptRunnableMapping == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("bind an interrupt to a runnable");
          cpb.rawPresentation("bind");
          props_InterruptRunnableMapping = cpb.create();
        }
        return props_InterruptRunnableMapping;
      case LanguageConceptSwitch.InterruptRunnableMappingActive:
        if (props_InterruptRunnableMappingActive == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("InterruptRunnableMappingActive");
          props_InterruptRunnableMappingActive = cpb.create();
        }
        return props_InterruptRunnableMappingActive;
      case LanguageConceptSwitch.InterruptRunnableReturnValue:
        if (props_InterruptRunnableReturnValue == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("retval");
          props_InterruptRunnableReturnValue = cpb.create();
        }
        return props_InterruptRunnableReturnValue;
      case LanguageConceptSwitch.InterruptTrigger:
        if (props_InterruptTrigger == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("interrupt");
          props_InterruptTrigger = cpb.create();
        }
        return props_InterruptTrigger;
    }
    return null;
  }
}
