package com.mbeddr.ext.units.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilder;
import jetbrains.mps.lang.dataFlow.DataFlowBuilderContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ConvertExpression_DataFlow extends DataFlowBuilder {
  public void build(final DataFlowBuilderContext _context) {
    _context.getBuilder().build((SNode) SLinkOperations.getTarget(_context.getNode(), LINKS.expression$LDUH));
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink expression$LDUH = MetaAdapterFactory.getContainmentLink(0xd04a6cc773e4069L, 0xb9b011884b2ff1c8L, 0x3930d8ab4c0e6285L, 0x3930d8ab4c0edbeaL, "expression");
  }
}
